### ISSUE TITLE
Expose gemini as global

### ISSUE THREAD

**Issue by SevInf** [gemini-testing/gemini#11]
Current code with explicit `var gemini = require('gemini');` has following problems:

- requires local `gemini` installation.
- requires `gemini` to **run** from local installation.

This can be solved if we'll expose `gemini` as global. We should also try to keep current API with explicit require working.

**Comment by DimitryDushkin** [comment]
+1

**Comment by sipayRT** [comment]
fixed in gemini v4.0.0
