### ISSUE TITLE
PhantomJS webdriver: Gemini throws error on image capturing if element has box-shadow 

### ISSUE THREAD

**Issue by sergesemashko** [gemini-testing/gemini#152]
Hi,

I'm getting the error below in PhantomJS webdriver, not sure if it's reproducible in other browsers:

```
StateError: Can not capture specified region of the page
The size of a region is larger then image, captured by browser
Check that elements:
 - does not overflows the document
 - does not overflows browser viewport
 Alternatively, you can increase browser window size using
"setWindowSize" or "windowSize" option in config file.
    at module.exports.inherit._validateImage (/usr/lib/node_modules/gemini/lib/capture-session.js:93:19)
    at /usr/lib/node_modules/gemini/lib/capture-session.js:42:27
    at _fulfilled (/usr/lib/node_modules/gemini/node_modules/wd/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/gemini/node_modules/wd/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/gemini/node_modules/q/q.js:756:13)
    at /usr/lib/node_modules/gemini/node_modules/wd/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/gemini/node_modules/wd/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
```

Reproducible on:
Ubuntu + PhantomJS 2.0.0
MacOS + PhantomJS 1.9

However, it works if box-shadow is overriden in executeJS callback:
```js
actions.executeJS(function (window) {
  // remove box shadow, sometimes gemini cannot capture image properly
  window.document.querySelector('.elem-box-shadow').style.boxShadow = 'none';
})
```

**Comment by SevInf** [comment]
Can you provide a test page for it?

**Comment by sergesemashko** [comment]
URL: http://sergesemashko.github.io/gemini-test/box-shadow.html

It fails on ```gather``` and ```test``` commands.

Test-case:
```js
var gemini = require('gemini');

gemini.suite('test-with-box-shadow', function (suite) {
  suite.setUrl('/gemini-test/box-shadow.html')
    .setCaptureElements('.box-shadow')
    .capture('default', function(actions, find) {
      actions.executeJS(function (window) {
        // uncomment line below to make test working
        //window.document.querySelector('.box-shadow').style.boxShadow = 'none';
      });
    })
});
```

**Comment by SevInf** [comment]
Ok, I've finally looked into this.
At first, let me explain how gemini is getting an area screenshot: it calculates position and size of element + outline + shadow, takes full page or viewport screenshot depending on the driver and crops it accordinly.
What happens in you case:  you have the block with default margins (8px in phantom) and box-shadow with 5px offset and 5px size. The total width of the element to screenshot is calculated as `blockWidth + shadowExtend`. In your case its `blockWidth + 10px` where `10px` is the shadow offset and size. The right age of this area is `blockWidth + 18px` (size + left margin).

PhantomJS driver can take only screenshot of the viewport. In your case viewport width is `blockSize + margins=blockSize + 16px`. So, right edge of your block's shadow is greater then viewport width and gemini can not crop the image accordingly, so it triggers the error.

Is it is accepatable, you can fix the issue either by increasing margin or decreasing shadow size.

**Comment by sergesemashko** [comment]
Updated gemini to the latest version and issue is gone. Not sure which release contains fix, but thanks for the reply anyway.
Closing the issue then.
