### ISSUE TITLE
Cannot screenshot "body" from Firefox

### ISSUE THREAD

**Issue by twolfson** [gemini-testing/gemini#176]
When using a Selenium based setup to capture a full page screenshot, I am encountering the following error:

```
StateError: Failed to capture the element because it is positioned outside of the captured body. Most probably you are trying to capture an absolute positioned element which does not make body height to expand. To fix this place a tall enough <div> on the page to make body expand.
Element position: 0, 0; size: 1426, 4253. Page screenshot size: 1426, 4252. 
    at module.exports.inherit._validateImage (/home/underdog/projects/scripts/project/node_modules/gemini/lib/capture-session.js:80:19)
    at /home/underdog/projects/scripts/project/node_modules/gemini/lib/capture-session.js:43:35
    at _fulfilled (/home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:796:13)
    at /home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:604:44
    at runSingle (/home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:137:13)
    at flush (/home/underdog/projects/scripts/project/node_modules/gemini/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)
Total: 1 Passed: 0 Failed: 1 Skipped: 0
```

My setup is as follows:

```yml
rootUrl: https://underdog.io
gridUrl: http://localhost:4444/wd/hub

browsers:
  chrome:
    browserName: firefox
```

```js
// Load in our dependencies
var gemini = require('gemini');

// Define our tests
gemini.suite('yandex-search', function (suite) {
  suite.setUrl('/')
    .setCaptureElements('body')
    .capture('plain');
});
```

Can we either add an exception case for the selector `'body'` that doesn't do the size check? Or maybe add a method for `capturePage()` that doesn't leverage `setCaptureElements` (and doesn't need a check)?

**Comment by twolfson** [comment]
Operating system info: Linux Mint 17.1 64 bit Cinnamon, Firefox 38.0

**Comment by SevInf** [comment]
It looks like 1px the difference appears due to a fractional value of `body.getBoundingClientRect`. Not sure what can be done about it. We often advocate against capturing the whole page for the following reasons:
- Majority of WebDriver implementations can not actually capture the page larger then viewport. Scroll-and-stitch strategy that is often advised in this case triggers unwanted scroll events and can produce unexpected side-effects, so we decided to avoid it.
- AFAIK, W3C WebDriver spec going to change screenshot method to "viewport only". [Link](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27661)
- Componentwise testing generally produce more consitent results and more clear reports.

So, if it is a viable option for you, I would recommend to switch to componentwise testing. If it is not, I will prefer not to have pagewise testing support in the core and leverage it to a plugin.

Let me know what you think about it and if you are still want to go pagewise route lets decide what Plugin API is necessary to support it.

**Comment by twolfson** [comment]
I think it would help if I gave more context to my situation. We are attempting to use Gemini during a CSS refactor; as a result, using anything component-specific isn't too practical as HTML/CSS structure is constantly shifting. The best we can do is to capture each page/possible state and see what changes we missed during the refactor.

If it won't be in core, I still think there should be something for easily testing at least the viewport state (there could prob be a plugin that does viewport + scrolling to capture it in non-fullpage viewport browsers).

**Comment by gunnx** [comment]
I understand that but is it useful for regression testing to see a full page, it can be left to phantomjs to cover that though? @twolfson

**Comment by twolfson** [comment]
We chose to use Firefox so it can get an accurate rendition of the page; PhantomJS doesn't typically capture fonts well and sometimes gets padding incorrect.

**Comment by gunnx** [comment]
@twolfson agree, I'd like the same. Have you any solutions right now?

**Comment by twolfson** [comment]
Yea, we forked `gemini` when we opened this issue to add the support we needed:

https://github.com/gemini-testing/gemini/compare/gemini-testing:30ff47d...underdogio:aed8d99

**Comment by gunnx** [comment]
Have you hosted that fork?
So it is just a case of updating capture-session.js and using
setCaptureElements('body')

**Comment by twolfson** [comment]
We are using the fork via `git`/`git+ssh` support in `npm`:

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

```
"gemini": "git://github.com/underdogio/gemini#aed8d99"
```

Yea, we use `setCaptureElements('body')` and it works

**Comment by gunnx** [comment]
Thanks I'll give that a go!

**Comment by gunnx** [comment]
@twolfson looks like that was against an older version, my config isn't working as is. I can get chrome and firefox to work but not phantomjs. capture-session.js has been rewritten since then.

**Comment by twolfson** [comment]
Ah, k. I think the logic should be transferrable but currently don't have time to look into this =/

**Comment by gunnx** [comment]
@twolfson no problem, thanks for your help.

**Comment by twolfson** [comment]
I tried this out on `gemini@3.0.2` and it seems to work. I'm going to close this issue as resolved :+1: 

**.gemini.yml:**

```yml
rootUrl: http://yandex.com

browsers:
  Firefox:
    desiredCapabilities:
      browserName: firefox
```

**index.js:**

```js
var gemini = require('gemini');

gemini.suite('yandex-search', function(suite) {
    suite.setUrl('/')
        .setCaptureElements('body')
        .capture('plain');
});
```
