### ISSUE TITLE
Change path of reporter

### ISSUE THREAD

**Issue by newtonianb** [gemini-testing/gemini#198]
How can I configure where the reporter generates the html file when I do `--reporter html` ?

**Comment by SevInf** [comment]
It is still not possible, which is a shame. I will gladly accept PR with this option. Otherwise, I will finally do it one of the next versions.

**Comment by just-boris** [comment]
+1

**Comment by sipayRT** [comment]
https://github.com/gemini-testing/gemini/pull/691
