### ISSUE TITLE
Disable overriding CLI arguments over API use in 0.13

### ISSUE THREAD

**Issue by DimitryDushkin** [gemini-testing/gemini#205]
We use API like this:

```js
new Gemini({ rootUrl: 'http://yandex.ru'});
gemini.gather(...);
```

This code is wrapped with our own CLI:
```bash
fiji gemini --root-url=yandex.ru
```
Then in our CLI we convert `yandex.ru -> http://yandex.ru/`. But this convertion is overriden by Gemini, so the final `root-url === 'yandex.ru'` NOT expected `http://yandex.ru/`.

This behaviour is broken in 0.13.

**Comment by SevInf** [comment]
Thanks for the report, this is the case we did not think about.
Does something something like:

```js
new Gemini({

}, {overrideWithEnv: false, overrideWithCli: false})
```

looks like good API for you?

**Comment by DimitryDushkin** [comment]
Maybe just disable it?) Seems like expected behavior when CLI arguments do not affect API call.

**Comment by SevInf** [comment]
Yes, sounds reasonable
