### ISSUE TITLE
Chrome mobile emulation not working correctly in 0.13

### ISSUE THREAD

**Issue by DimitryDushkin** [gemini-testing/gemini#206]
We have browser config for smartphone like this:

``` js

'touch-phone-chrome': {
        desiredCapabilities: {
            browserName: 'chrome',
            calibrate: false,
            chromeOptions: {

                mobileEmulation: {

                    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X)'
                        + ' AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4',
                     deviceMetrics: {

                         width: 320,
                         height: 568,
                         pixelRatio: 1

                     }

                }
            }
        }
    }
```

This config sets mobile emulation for chrome like emulation in dev tools. In 0.13 if `deviceMetrics` is set, gemini do not begin tests. If `deviceMetrics` is missing everything is okay.

For now we use `windowSize: '320x568'` as workaround, but it will be great if you fix `deviceMetrics` that desired `pixelRatio` works.

**Comment by SevInf** [comment]
>In 0.13 if deviceMetrics is set, gemini do not begin tests
It is interesting. As it correct that it worked for you until you upgraded to 0.13.0? I've tried chrome mobile emulation few months ago (around first 0.12.x versions) and gemini failed to capture the images properly.  If it worked for you,  I'll be very curious about the settings you used.

Closer to the issue, mobile browser (including emulation) is not officially supported in current version, but it is our main priority for the next major update. So, this issue will likely be solved in a next few weeks and   Chrome with enabled emulation will be added to our functional test suite.

**Comment by DimitryDushkin** [comment]
Yes, on 0.12 mobileEmulation works on such config:

```js
    'touch-phone-chrome': {
        browserName: 'chrome',
        '--noCalibrate': 'true',
        chromeOptions: {

            mobileEmulation: {

                userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X)'
                    + ' AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4',
                deviceMetrics: {

                    width: 320,
                    height: 568,
                    pixelRatio: 1

                }

            }
        }
    },
```

Only issue with this is visible scrollbar. But this was okay for our tests.

**Comment by sipayRT** [comment]
fixed for a long time ago
