### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by beam018** [gemini-testing/gemini#215]
Hi!

I have an error on Gemini launch: "Segmentation fault: 11".
Gemini runs with js wrapper via API.

Version: 0.13.2
Node: 0.12.7

NODE_PATH:
```
beam@95:~/work/gt > echo $NODE_PATH
./node_modules:/Users/beam/.nvm/versions/node/v0.12.7/lib/node_modules
```

Error log:
```
beam@95:~/work/gt > DEBUG=fiji* fiji gemini gather --root-url yandex.ru --browsers=desktop-chrome
  fiji Получили на вход ["node","/Users/beam/work/gt/bin/fiji","gemini","gather","--root-url","yandex.ru","--browsers=desktop-chrome"] +0ms
  fiji:gemini Запускаем gemini тесты в /Users/beam/work/gt/e2e/gemini +7ms
  fiji:gemini   reporters: flat,html +0ms
  fiji:gemini   gridUrl: http://localhost:4444/wd/hub +0ms
  fiji:gemini   browsers: ["desktop-chrome"] +0ms
  fiji:gemini   resolution: 1440x768 +0ms
  fiji:gemini   rootUrl: http://yandex.ru/ +0ms
Segmentation fault: 11
```

How to fix this?

**Comment by arikon** [comment]
@beam018 What OS are you on?

**Comment by arikon** [comment]
@beam018 Could you provide .core file?

**Comment by beam018** [comment]
OS: OS X Yosemite 10.10.5 (14F27),
core file: https://yadi.sk/d/385PweXGiVzC8

**Comment by arikon** [comment]
@j0tunn Have a look, please

**Comment by dab** [comment]
:+1:

**Comment by j0tunn** [comment]
В общем core-file я сходу посмотреть не смог, а закапываться туда пока времени не было. Если есть шаги воспроизведения - это бы полечило

**Comment by beam018** [comment]
On node 0.10 all OK

**Comment by beam018** [comment]
@j0tunn, я попросил @dab дойти до тебя. Надеюсь у вас все полйчиться =)

**Comment by j0tunn** [comment]
There was some problem in `nan` with using static map in ObjectWrap, which was fixed in https://github.com/nodejs/nan/pull/431. Should work with `nan@2.0.8` (`png-img` dependency)

**Comment by arikon** [comment]
:+1:
