### ISSUE TITLE
Don't throw error if some capture elements are missing

### ISSUE THREAD

**Issue by fenduru** [gemini-testing/gemini#231]
I'm trying to test a dropdown component that opens up additional content when the button is clicked. The content is `position: fixed`, so in order for the screenshot to be correct I need to include the content as a capture element. The problem is that the first capture in the suite takes an image *before* the dropdown is open, so [an error is thrown here](https://github.com/gemini-testing/gemini/blob/master/lib/browser/client-scripts/gemini.js#L76)

I think the simplest solution would be to treat all elements as optional, and `continue` the for loop instead of returning an error. Then after the loop, ensuring that there is *some* rectangle to capture, and throwing an error at that point if none of the elements were present.

Thoughts?

**Comment by SwinX** [comment]
Please see my answer in #282. Hope it will help you with your issue.
