### ISSUE TITLE
Possibility to apply array of suits into gemini.test

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#247]
Description: https://ru.bem.info/forum/598/

More info:

When providing the array of files with tests into `gemini.test` (or `gemini.gather`) it is not possible to modify the content of the tests. Crucial when all the gemini functionality is wrapped in plugin.

**Comment by SwinX** [comment]
Seems this may now be done using [SuiteCollection](https://github.com/gemini-testing/gemini/blob/master/doc/programmatic-api.md#suite-collection) in programmatic API.
