### ISSUE TITLE
Improve gemini events documentation

### ISSUE THREAD

**Issue by SwinX** [gemini-testing/gemini#265]
Propose to add following:
- Gemini and runner events order scheme.
- For each event add documentation about data passed to listeners on event.
- Mark events which execution gemini will wait (i.e. gemini will wait until promise returned from event listener)

**Comment by SwinX** [comment]
As evolution of this task we may want to somehow improve\refactor current event system

**Comment by Dmitriy-kiselyov** [comment]
All events are already described in documentation
