### ISSUE TITLE
Setting gridUrl from programmatic api not publicly available

### ISSUE THREAD

**Issue by smoogly** [gemini-testing/gemini#267]
In gemini 1.0.4 setting gridUrl with:

``` javascript
var g = new Gemini(__dirname + '/config.yml', {
  gridUrl: '<myGrid>'
});
```

and with:

``` javascript
g.test(['<myTest.js'>], {
  gridUrl: '<myGrid>'
});
```

doesn't works.
The only way I've found to set gridUrl programmatically requires accessing a private field:

``` javascript
g.config._configs[browser].gridUrl = '<myGrid>';
```

Is it a bug, a desired behavior or am I missing something?

**Comment by smoogly** [comment]
Same problem with rootUrl.

**Comment by Dmitriy-kiselyov** [comment]
Already fixed
[Proof](https://gemini-testing.github.io/doc/programmatic-api.html)
