### ISSUE TITLE
Feedback for "Введение в работу с Gemini"

### ISSUE THREAD

**Issue by jifeon** [gemini-testing/gemini#268]
https://ru.bem.info/tools/testing/gemini/

Целая куча описок в конфигах. Вместо desiredCapabilities почти везде de**sri**edCapabilities. Из-за этого не работают почти все конфиги на главное странице про gemini...

**Comment by arikon** [comment]
@jifeon Можешь прислать pr с исправлениями?

**Comment by jifeon** [comment]
Выглядит как будто кто-то уже поправил
