### ISSUE TITLE
Gemini shows diff on identical screenshots

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#270]
Visually identical screenshots are considered different. the problem is with the transparent parts.
https://yadi.sk/d/ipq4WTLGjsKHs

Reference screenshots are taken with PhantomJS on Yosemite
The tests are run on El Capitano

We tried to fix this with `tolerance`, but this did not help.

Is it possible to teach Gemini to consider these 2 kinds of transparent as the same?

**Comment by varya** [comment]
UPD: The problem is not with transparent parts but with something else. I tried with white background and got the same mismatch however the screenshots look identical.

**Comment by j0tunn** [comment]
![diff](https://yadi.sk/i/TJpHFk-2k27gh_XL.png)

**Comment by varya** [comment]
Why do you close? The picture you provided demonstrates that screenshots may be different without any change from a user. It's it a problem when testing?

**Comment by j0tunn** [comment]
OS upgrade (and browser upgrade) is a major change from user. Different OSes render fonts differently.

**Comment by varya** [comment]
Yes, this is my request. Is it possible to teach Gemini not to consider font render differences? Otherwise the usage of Gemini would require all the devs to use the same OS when developing which sounds too pushy.

**Comment by j0tunn** [comment]
In general the answer is NO, this is not possible. Gemini knows nothing about fonts, it deals with images. However we are working right now on images comparison improvement. See issues in `looks-same`: https://github.com/gemini-testing/looks-same/issues

**Comment by varya** [comment]
Good. If the library Gemini uses will take it into account, this is completely an answer to my question. Thank you!
