### ISSUE TITLE
New session request was cancelled before a Sauce Labs virtual machine was found

### ISSUE THREAD

**Issue by elgalu** [gemini-testing/gemini#272]
Sometimes Saucelabs take up to 90 seconds to allocate a VM, particularly slower for mobile devices, so 2 issues here:

1. `npm test` just halts forever

2. I can't find the place to increase the default timeout for `POST /wd/hub/session`, if possible.

#### Screen shots
for 1.
![npm-test_hangs_on_saucelabs_errors_console](https://cloud.githubusercontent.com/assets/111569/10610162/efaa110a-7746-11e5-9537-b90bbfbf420e.png)

for 2.
![npm-test_hangs_on_saucelabs_errors_dashboard](https://cloud.githubusercontent.com/assets/111569/10610116/c2c33fcc-7746-11e5-97a8-1f7962e893e7.png)

Sauce Labs message:
> Your test errored. New session request was cancelled before a Sauce Labs virtual machine was found For help, please check https://docs.saucelabs.com/reference/troubleshooting-common-error-messages

**Comment by elgalu** [comment]
Also tried `httpTimeout: 90000` but didn't help

**Comment by j0tunn** [comment]
Could you provide:
* debug output (use DEBUG=* env var)
* used gemini version

**Comment by elgalu** [comment]
Sure,

* debug out put [gist](https://gist.github.com/elgalu/43dc9c918553741aed17#file-npm_test-log-L6278)
* gemini version: master branch as of today.

Also Sauce Labs links where the error "cancelled before a Sauce Labs virtual machine was found" happened:

#### iOS 7.1
https://saucelabs.com/beta/tests/1d7242475ae7437f92523c2744923831
https://saucelabs.com/beta/tests/4a078af433a24f82ba0cb60fb6888fd9
https://saucelabs.com/beta/tests/ff9ebf72de6a468c86719d6996e0759e

#### iOS 8.1
https://saucelabs.com/beta/tests/9047a9f8d9654cbea82c32c73ab89654
https://saucelabs.com/beta/tests/56cf4b6c11984f77a051d2651883e9d5
https://saucelabs.com/beta/tests/d217012a23d14a8db3c4518141ed5982
https://saucelabs.com/beta/tests/4b34274dbb7b4ada89639037e974b6e0
https://saucelabs.com/beta/tests/47cf84f688b2426cb9dca6636904e695
https://saucelabs.com/beta/tests/8a7c3162ebb5435f8501f2120e2c793e
https://saucelabs.com/beta/tests/72628ec1af3c49759db75bf9ffd657d2
https://saucelabs.com/beta/tests/8441833c789a4dbcbdacb6eb7b71eeb0

#### iOS 8.4
https://saucelabs.com/beta/tests/263a8edc8cde43e7abef711e94d5f029
https://saucelabs.com/beta/tests/9c0c763b5a614c3b99e9a2cfe1822cbd

#### iOS 9.0
https://saucelabs.com/beta/tests/6f27fc338bed478dba0c026e64691eb1
https://saucelabs.com/beta/tests/850e8b7504574c4d923907ce02e63bf0

#### Android 5.0 Browser
https://saucelabs.com/beta/tests/9d9bc034c750480e94390c615d180160

#### Android 4.0 Browser
https://saucelabs.com/beta/tests/615c585d67b04d22bb25564dbafafb7b

#### Android 4.0 Chrome
https://saucelabs.com/beta/tests/15f561baeefc4866b720a518c6ab90ea
https://saucelabs.com/beta/tests/5d8e2098a90c43f2829241ff28d0a2e8

**Comment by SwinX** [comment]
This issue looks really strange. Are you sure that `90000ms` is really enough? Have you tried to increase it more?

**Comment by SwinX** [comment]
Closing due to reporter inactivity https://github.com/gemini-testing/gemini/blob/master/CONTRIBUTING.md#issues-reporting

**Comment by SrimanPilli** [comment]
Similar error, any solution yet ?
Thanks

**Comment by DudaGod** [comment]
Hello.

Gemini is not supported anymore. Try to use our new tool - [hermione](https://github.com/gemini-testing/hermione) which can compare screenshots like gemini.

**Comment by SrimanPilli** [comment]
@DudaGod thanks for reply.
I might be in wrong thread. I am facing this error in Sauce Labs Appium UI tests
