### ISSUE TITLE
Possibility to provide "accepted diff" for pending tests

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#273]
This is a new feature proposal.

Sometimes it may happen that certain kind of diff is accepted but others are not. It would be nice if I could provide "accepted diff" as a path to a diff picture, and the test which gives mismatch exactly as this "accepted diff" would be considered pending.

**Comment by j0tunn** [comment]
Could you provide some use cases? For now it looks like some hack to avoid unstable tests

**Comment by SwinX** [comment]
Closed due to reporter inactivity: https://github.com/gemini-testing/gemini/blob/master/CONTRIBUTING.md#issues-reporting
