### ISSUE TITLE
Generated filename from suit must contain only [A-Za-z0-9-_\.]

### ISSUE THREAD

**Issue by levonet** [gemini-testing/gemini#276]
Сейчас название сюта совпадает с названием файла.
Например
`gemini.suite('bla bla bla/olol=1'….`
генерирует файл `bla bla bla/olol=1/plain/firefox.png`.
Хочется чтобы gemini оставил в название файла только `a-z0-9-_.`
`'bla bla bla/olol=1/plain/firefox.png' —> 'bla_bla_bla/olol_1/plain/firefox.png'`

**Comment by SevInf** [comment]
Мы же не в 91 году, все ФС умеют пробелы.
Если очень хочется, то почему бы просто сьют не называть `bla_bla_bla`?

**Comment by levonet** [comment]
\cc @shuhrat @arikon @j0tunn

**Comment by levonet** [comment]
Речь здесь не только про пробелы, можно в названии сьюта указать спецсимволы, такие как `!?*\`,  это в теории может вызвать проблемы при работе с github.

**Comment by SevInf** [comment]
Так почему бы просто так не делать?

**Comment by j0tunn** [comment]
имеет смысл это валидировать

**Comment by fenduru** [comment]
https://www.npmjs.com/package/slug

**Comment by j0tunn** [comment]
мне кажется, что да
