### ISSUE TITLE
Ability to set in config path to tests

### ISSUE THREAD

**Issue by j0tunn** [gemini-testing/gemini#278]
For now gemini reads test files from `./gemini` directory. It would be nice to make it configurable.
Also one should be able to use wildcards in configuration: `./**/gemini/*.test.js` (or smth)

**Comment by SevInf** [comment]
`gemini test <other path>` ?

**Comment by j0tunn** [comment]
wildcards?

**Comment by SevInf** [comment]
Wildcards expansion is a job for shell, not a tool

**Comment by j0tunn** [comment]
Yeah, but I was thinking about more convenient wildcards, not just `./*/*/*/gemini/*.js`

**Comment by SevInf** [comment]
zsh & bash 4+ understand `**`, `{thing1,thing2}` and other advanced glob patterns

**Comment by SevInf** [comment]
Just out of curiusity, why "I can not install gcc 4.6" is "Fuck you, its not our problem, go get some updates, grandma" but "I can not install bash 4" is so important that we need to replicate shell functionality in our tool? Bash4 have been released in 2009, gcc 4.6 in 2011.

**Comment by arikon** [comment]
Ability to specify tests mask in config is a convenient feature. It will let you run just `gemini test` to run all the project tests spread among BEM-like directory structure.

**Comment by SevInf** [comment]
You can do this now:

```
gemini test *.blocks/**.gemini.js
```

**Comment by j0tunn** [comment]
The point is to run `gemini test` instead of `gemini test some-glob-pattern-with-lots-of-*`

**Comment by sipayRT** [comment]
works from 4.5.0
