### ISSUE TITLE
Unable to set windowSize of PhantomJS until after launch

### ISSUE THREAD

**Issue by davidchin** [gemini-testing/gemini#289]
I tried to configure `windowSize` of PhantomJS in `.gemini.yml` but it didn't seem to work. I tried to set it at the top level and browser level - both didn't take an effect. For example:

~~~{yaml}
browsers:
    phantomjs:
        windowSize: 1200x800
    phantomjs-xsmall:
        windowSize: 480x800
~~~

However, when I tried to configure `windowSize` for individual tests, it worked. For example:
~~~{js}
suite.before(function(actions) {
    actions.setWindowSize(480, 800);
})
~~~

I tried using a different browser, say, Chrome, and both methods worked as expected.

I had a look at `Browser#launch` method. It seemed the config values were passed to the driver correctly when `_setDefaultSize` was called. But the changes were reverted when `_maximize` was called in the next promise chain. This method was only called for PhantomJS - that explained why it worked for other browsers.

ac0549ea249e6b97a020e7e11344280bf07a9a2c seems to be the commit that introduced this odd behaviour. I assume it is a browser-specific workaround? Should it be changed so that this workaround only applies if `windowSize` setting is not configured in `.gemini.yml`? Or more importantly, is the workaround still applicable?

**Comment by SwinX** [comment]
@davidchin seems this behavior was introduced in some ancient age to deal with strange `phantom.js` issue when by default it's windows size was extremely small.
Seems your PR completely resolves described issue, closing it now.
