### ISSUE TITLE
Document the reporter API

### ISSUE THREAD

**Issue by fenduru** [gemini-testing/gemini#293]
I'm interested in writing my own reporter, however the events broadcasted by the runner are not documented (I don't want to rely on undocumented behavior). Would be great if these events could be documented

**Comment by SwinX** [comment]
@fenduru, sure, this needs to be done. Thank you for reporting!

**Comment by Dmitriy-kiselyov** [comment]
All events are already described in documentation
[Proof](https://gemini-testing.github.io/doc/events.html)
