### ISSUE TITLE
Feedback for "Введение в работу с Gemini"

### ISSUE THREAD

**Issue by myryasha** [gemini-testing/gemini#299]
Добрый день, в примерах написания файлов .gemini.yml ошибка в "desriedCapabilities:"

rootUrl: http://yandex.com
gridUrl: http://selenium.example.com:4444/wd/hub

browsers:
  chrome:
    de__sir__edCapabilities:
      browserName: chrome
      version: "45.0"

  firefox:
    de__sir__edCapabilities:
      browserName: firefox
      version: "39.0"

**Comment by sipayRT** [comment]
спасибо, поправили
