### ISSUE TITLE
_this.emit is not a function

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#304]
I'm trying to run the yandex-search example you have on the main page, but it's coming up with this error:

✘ yandex-search plain [PhantomJS]
_this.emit is not a function
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0
Critical error while running " yandex-search plain" in PhantomJS:
TypeError: _this.emit is not a function
    at /Users/van.patton/node_modules/gemini/lib/capture-processor/screen-shooter.js:31:23
    at _fulfilled (/Users/van.patton/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/van.patton/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/van.patton/node_modules/q/q.js:796:13)
    at /Users/van.patton/node_modules/q/q.js:604:44
    at runSingle (/Users/van.patton/node_modules/q/q.js:137:13)
    at flush (/Users/van.patton/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

I start phantomjs using phantomjs --webdriver=4444
then I run the test using   gemini gather test

.gemini.yml
rootUrl: http://yandex.com
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs

test.js
var gemini = require('gemini');

gemini.suite('yandex-search', function(suite) {
    suite.setUrl('/')
        .setCaptureElements('.main-table')
        .capture('plain')
        .capture('with text', function(actions, find) {
            actions.sendKeys(find('.input__control'), 'hello gemini');
        });
});

**Comment by vpatton** [comment]
nm just installed 1.1.2 and its working now

**Comment by sipayRT** [comment]
yes, sorry. It was bug in the `gather` command in `v1.1.1` version. Was fixed in `v1.1.2`
