### ISSUE TITLE
Using a series of Capture, but it only captures the last one stated 

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#305]
var gemini = require('gemini');

gemini.suite('BeerFriday landing page', function(suite) {
    suite.setUrl('thispage.cms.dev.thisSIte.com')
        .setCaptureElements('div.ddc-content.header-value-statement')
        .capture('header');
    suite.setCaptureElements('.slick-track')
        .capture('model selector');
    suite.setCaptureElements('div[data-widget-id="content1"]')
        .capture('default content');
    suite.setCaptureElements('.vs-header-container')
        .capture('static value statement container');
    suite.setCaptureElements('div[data-widget-name="content-hero"]')
        .capture('content');
});

When I run the test using phantomjs it takes the screenshots but they are all of the last one suite.setCaptureElements('div[data-widget-name="content-hero"]')  
If I remove the two lines,     
suite.setCaptureElements('div[data-widget-name="content-hero"]')
        .capture('content'); 
then run the tests again, the screenshots taken are all of     
suite.setCaptureElements('.vs-header-container')
        .capture('static value statement container');
it was working fine for awhile, until I added the 5th suite.setCaptureElements

**Comment by sipayRT** [comment]
In your case you override `setCaptureElements` for the same suite. Please, see example from the documentation - https://github.com/gemini-testing/gemini/blob/master/doc/tests.md#nested-suites

**Comment by SwinX** [comment]
@vpatton please let us know will solution provided by @sipayRT helped.

**Comment by vpatton** [comment]
Yes it does thank you, now I remember why I tried that.  I was trying to avoid the "Each new suite causes reload of the browser, even if URL was not changed." If you have all of the elements on the same page, it can be rather time consuming to reload the browser every time.   I did have it working for awhile like that, (not reloading each time) but it must have been a fluke

**Comment by SwinX** [comment]
@vpatton nice to hear it helped. Closing issue now.
