### ISSUE TITLE
Refactor skip method

### ISSUE THREAD

**Issue by SwinX** [gemini-testing/gemini#311]
Required changes:
* Possibility to add comment to skip for each skipped browser
* If skip specificator is a string then match browser ids, not browser name
* Need to match browser ids using regexp pattern.
* Need to remove ability to skip browser using browser name and version

According to this changes API need to be following:

* `suite.skip()` - skips suite in all browsers, without comment
* `suite.skip('chrome-latest')` - skips suite for browser with ID `chrome-latest`, without comment
* `suite.skip(/ie.+/)` - skips suite for browsers with ID matching `/ie.+/`, without comment
* `suite.skip(/(.*?)/, 'because reasons')` - skips suite for all browsers, adds comment `because reasons`

Skip for multiple browsers need to be following: 
``` js
suite.skip([
        'firefox-latest',
        /(chrome-+)/,
    ], 'because reasons');
``` 
This will skip suite for browser with id `firefox-latest` and all browsers with IDs containing `chrome-`, for each browser adds comment `because reasons`

Support for appending browsers to skip via multiple skip calls must not be changed - this way we would be able to skip multiple browsers with different comments.

**Comment by SwinX** [comment]
Also need to add skip reason to flat and HTML reporters

**Comment by SevInf** [comment]
Why not use regular expression instead of glob patterns?

```js
suite.skip(/ie.+/)
```

Regex are native to JS and clearly distinguishable from strings, so we can:
1. Don't add ours or third-party code for glob matching
2. Use cheap string comparison for strings

**Comment by SevInf** [comment]
Also, do we need to keep `{browserName, version}` API?
You can do everything you need with browserId + regex and we are breaking API anyway

**Comment by SwinX** [comment]
> Why not use regular expression instead of glob patterns?

Glob patterns seems to be easier to read. About cheap string comparition - it seems that `minimatch` already can do this.

> Also, do we really need to keep {browserName, version} API?

There may be some cases when we need this. For example we had browser with ID `iphone`, but actually that was chrome with small size =). Also we may want to skip for exact browser version if found some specific browser-related bug (hello ie8) and skipping by browser name and version may be more obvious.

**Comment by leonsabr** [comment]
As I understand we provide the only single comment for all skipped browsers? We don't want to specify the reason for each browser, do we?

**Comment by SevInf** [comment]
>Glob patterns seems to be easier to read

Regex are more powerful and native to JS. Glob patterns primary usage is file paths, not any arbitrary string. 

>it seems that minimatch already can do this.

But you need to match every string with minimatch when with regex it can be:

```javascript
if (typeof pattern === 'string') {
    return pattern === file;
} else if (pattern instanceof RegExp) {
   return pattern.test(file)
}
```

> Also we may want to skip for exact browser version if found some specific browser-related bug (hello ie8)

`.skip('ie8')` is as obvious (or even more) then `.skip({browserName: 'internet explorer', version: 8})`

**Comment by j0tunn** [comment]
* regexp instead of glob patterns - ok
* `{browserName, version}` - it is common case to skip by browser name. Version... yes, a less common, but still usable: lets pretend that we have dozens of browser specifications with different capabilities (how about window size?) and different ids for them. Also we will need to fix all that skips that are there in the code now. And by the way we already have that code, so we pay nothing for that feature.

**Comment by SevInf** [comment]
>lets pretend that we have dozens of browser specifications with different capabilities (how about window size?) and different ids for them.

This exactly what regexps are for: `/chrome.+/`, `/chrome-(largeScreen|smallScreen)/`, `/ie-(8|9)/`

>Also we will need to fix all that skips that are there in the code now

There were far more `.skip('browserName')` in the code as far as I remember, so you'll need to fix it anyway.

> And by the way we already have that code, so we pay nothing for that feature.

We need to maintain the existing code.

**Comment by j0tunn** [comment]
> This exactly what regexps are for: /chrome.+/, /chrome-(largeScreen|smallScreen)/, /ie-(8|9)/

Ok, what about browser with id `iphone`, that in fact is a `chrome` with small window size? Thats all about naming, and we shouldn't add any restrictions on that, `{browserName: 'chrome', version: '42'}` looks much more simple than `/^(iphone)|(chrome-(largeScreen|smallScreen))|(any-other-stupid-name)$/`, don't you think? We should add the abilities, not remove them.

**Comment by SevInf** [comment]
Then why skip by id at all? Ids are arbitrary and user-specified, browser names and version are fixed.

**Comment by j0tunn** [comment]
Because it is handy :)

**Comment by SevInf** [comment]
So handy that we are breaking feature that has existed in its current form almost from the begining of the project without any prior waring?

**Comment by j0tunn** [comment]
Doh! I see the reason why it would be nice to remove that ability to skip by browser name/version: we should get browser session first, and thats bad.
Ok, I agree :) Lets remove that feature.

**Comment by SwinX** [comment]
According to following discussion, updated new requirements for `skip`.
