### ISSUE TITLE
Refactor `gather` command

### ISSUE THREAD

**Issue by SwinX** [gemini-testing/gemini#312]
Need to rename it to `update`. Add 2 keys for command: `--diff` and `--new`.
Behavior needs to be following:

`gemini update`: adds reference images for suites without them, updates references for suites with diff
`gemini update --diff`: updates only references for suites with diff.
`gemini update --new`: adds only missing references for suites

**Comment by SevInf** [comment]
`gemini update --diff` don't we have a gui for that?

1. We have
2. This command wil make gather work like test, cause a major rewrite, bring the whole lot of new bugs as retries did
3. The command will encourage users to update images without looking at the diff
