### ISSUE TITLE
Compare screenshots and calculate diff in separate process

### ISSUE THREAD

**Issue by SwinX** [gemini-testing/gemini#314]
Need to do this in specific worker pool.

**Comment by SevInf** [comment]
Can we do measurments before merging this? `looks-same` does not block event loop for comparing and creating diff and the biggest bottleneck is still communication with WebDriver.

**Comment by SwinX** [comment]
![2015-11-20 12-16-07 si -- serp -- web4 -- dev -- 2 gemini -- desktop - 5 19 nov 15 22-08 - perfmon teamcity](https://cloud.githubusercontent.com/assets/854899/11531544/b03eb702-990e-11e5-861b-b36dbb96a823.png)

We have following CPU load graph. AVG 20% load represents full load of single core.

**Comment by SevInf** [comment]
Can we see before/after graphs after this feature is ready?
