### ISSUE TITLE
Remove strictComparison option

### ISSUE THREAD

**Issue by SevInf** [gemini-testing/gemini#320]
From a user point of view its the same as `tolerance: 0`. AFAIK it never really have been used by anyone and I can not imagine how can it be useful in real world scenarios. The same can probably be done for looks-same.

**Comment by j0tunn** [comment]
PR? :)

**Comment by SevInf** [comment]
Of course. Just wanted to know if anyone have an objections first.

**Comment by sipayRT** [comment]
:+1:
