### ISSUE TITLE
ignoreElements should honor z-index

### ISSUE THREAD

**Issue by apsavin** [gemini-testing/gemini#328]
```js
gemini.suite('popup ' , function (child) {
            child
                .setUrl('url/to/page')
                .before(function (actions, find) {
                    actions.setWindowSize(1200, 800);
                    actions.click(find('.show-popup'));
                    actions.waitForElementToShow('.popup', 2000);
                })
                .ignoreElements('.footer')
                .setCaptureElements('.popup')
                .capture('plain');
        });
```

Part of image before line `.ignoreElements('.footer')` was added:
https://www.dropbox.com/s/uycnpw1epvbxd9e/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-08%2020.01.40.png?dl=0

After:

https://www.dropbox.com/s/e0hexjvsegsjcxe/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-08%2020.02.21.png?dl=0

Expected result:

footer ignored, but not elements above.

**Comment by sipayRT** [comment]
in this case wd just paint over position of the footer on the screen, not on the page. If you test live page without possibility to change popup position or footer CSS, so you can try that hack like

```
.capture('popup', function(actions) {
    actions
        .executeJS(function(window) {
            window.$('.footer').css('opacity', 0);
        })
        .click('.show-popup')
        .waitForElementToShow('.popup', 2000);
});
```

**Comment by apsavin** [comment]
ok, thanks!

**Comment by hjri** [comment]
I'd say it should be fixed - using such hacks in tests is outrageous. If anything - gemini should provide a method that does just that or fills element with set color (black is bad if popup has shadow).
