### ISSUE TITLE
API for testing one suite

### ISSUE THREAD

**Issue by j0tunn** [gemini-testing/gemini#332]
The idea is next.
`gemini` provide `SuiteCollection` interface, which can be used to create custom suite collection. And `gemini.test` can accept `SuiteCollection` instance as a first argument.

`SuiteCollection` API:
* read tests from files. Like `gemini.readTests` do, so we can deprecate it some day
* add separate suites with some specifications (states to run, for example)
* return rootSuite
* return flat suite list

Usage example:
```js
var suiteCollection = new gemini.SuiteCollection();
        .addSuite(suite1)
        .addSuite(suite2, ['ie8', 'ie9'])
        .addSuiteStates(suite3, ['state2', 'state4'])
        .addSuiteStates(suite4, {
            'state2': ['ie8', 'ie9'],
            'state4': ['chrome']
        });

return gemini.test(suiteCollection, options);
```

`Suite` will have new field `captureMap`, which would be used in `SuiteRunner` and `StateRunner` to determine which states should be captured in which browsers.
If some state not specified in `captureMap` than screenshot will not be taken and `END_TEST` event will not be emitted, but `START_STATE` and `END_STATE` will be emitted and all actions and its callback will be performed

**Comment by j0tunn** [comment]
@SevInf @arikon @SwinX @sipayRT

**Comment by j0tunn** [comment]
Description updated

**Comment by SevInf** [comment]
I'm not quite sure what problem does it solve. Can you add more details?

**Comment by j0tunn** [comment]
It adds ability to run single state. For example using gemini-gui: https://github.com/gemini-testing/gemini-gui/issues/5

**Comment by j0tunn** [comment]
And also it will close https://github.com/gemini-testing/gemini/issues/247

**Comment by SevInf** [comment]
Got it.
For GUI purposes s bit different API might be more useful. Instead of `.addSuiteState(suite, [states])` it might be useful to do this instead:

```js
collection.addSuite(suite)
collection.disableState(suite, 'state')
collection.enableState(suite, 'state')
```

**Comment by j0tunn** [comment]
How about browsers? What if I need to run only on state in one browser (in fact the more common case for gemini-gui)?

**Comment by j0tunn** [comment]
There is a case to think about:
```js
var suiteCollection = new gemini.SuiteCollection(paths),
    otherCollection = new gemini.SuiteCollection();

// Add some suite form suiteCollection to otherCollection
otherCollection
    .add(someSuite1)
    .add(someSuite5);
```

What should be the rootSuite of `otherCollection`? Do we really need the ability to get rootSuite of a collection, or all we need is just the ability to iterate over suites in some collection?

**Comment by SevInf** [comment]
I don't think we need root suite that much. It was just a convinience data sturucture from the times we had no public API, did not provide much usefulness to consumers when we got one and original convenience became not relevant when we started flattening suites before running.

**Comment by SevInf** [comment]
>How about browsers? What if I need to run only one state in one browser (in fact the more common case for gemini-gui)?

We already have `browsers` option in both `test` and `gather` methods, this and ability to run only selection of states should be enough.

**Comment by j0tunn** [comment]
Yes, but don't we need the ability to run this state in this browser and that state in that browser?

**Comment by SevInf** [comment]
Do you have any sketches of how it will look like in GUI? I imaging doing it will be more cumbersome then check this state, check this browser, run tests, check that state, check that browser, run tests.

**Comment by j0tunn** [comment]
In GUI it can look like number of checkboxes and button "Run selected"

**Comment by SevInf** [comment]
Ah, thats simple. Ok then. Still I think enable/disable API will be more convinient for GUI purposes so we won't be building a new collection before each run. So, maybe this one will fit better:

```js
collection.addSuite(suite)
collection.disable(suite) // disables suite, its children and it states
collection.disable(suite, 'state') // disable one state
collection.disable(suite, 'state', ['browserA'], ['browserB']) // disable subset of the browsers

collection.enable... // takes same parameters as disable

collection.enableAll()
collection.disableAll()
```

**Comment by j0tunn** [comment]
Looks good. And how do we disable (enable) whole state in certain browser(s)?

**Comment by SevInf** [comment]
Not sure if it will be easy to do with checkbox list, but we can treat each parameter as optional, so it will be `.disable(suite, null, ['browser'])`. Or just assume that browsers always be an array and shorten it to `.disable(suite, ['browser'])`.`

**Comment by j0tunn** [comment]
Lets summarize.
```js
 // Create collection
var suiteCollection = new gemini.SuiteCollection(); // empty
var suiteCollection = new gemini.SuiteCollection(paths); // parse test files

// Add suite
suiteCollection.addSuite(suite) // How about just suiteCollection.add(suite); ?

// Enable/disable
suiteCollection.enableAll(); // enable all suites
suiteCollection.enable(suite); // enable suite states or its children suites recursively
suiteCollection.enable(suite, ['browserA', 'browserB']); // enable suite states or its children in specified browsers
suiteCollection.enable(suite, 'state'); // enable suite state
suiteCollection.enable(suite, 'state', ['browserA', 'browserB']); // enable suite state in specified browsers
// All the same for disable

// List suites in collection
suiteCollection.list(); // list top level suites, which were parsed from files or added by addSute
suiteCollection.flatList(); // scan from top level suites down and get flat list of suites
```

Enable/disable methods will create `suite.launchMap` field, which will be used in runner to decide what shoud be launched.
Disabled states means that we will not take screenshot for it, but will perform all its action.
Disabled suite means that it will be silently skipped (no events will be emitted).

**Comment by SevInf** [comment]
>How about just suiteCollection.add(suite); ?
:+1: 
>suiteCollection.list();
>suiteCollection.flatList()

I would be more explicit and call it `topLevelSuites()` and `allSuites()`
