### ISSUE TITLE
Remove ru doc

### ISSUE THREAD

**Issue by j0tunn** [gemini-testing/gemini#337]
Lets leave only english doc. Its very annoying to support both.

**Comment by j0tunn** [comment]
@SevInf @arikon @SwinX

**Comment by SevInf** [comment]
I would generally agree, but what about http://bem.info? Currently, russaian and english docs are published there, will they be ok with only English?

**Comment by SwinX** [comment]
@SevInf Y.Translate to the rescue!

**Comment by vithar** [comment]
I suggest to move Gemini to separate site from bem.info. Gemini is not bem related tool and I see no reasons to keep it on ben.info.
