### ISSUE TITLE
Difficulties with different browser sizes

### ISSUE THREAD

**Issue by lyptt** [gemini-testing/gemini#338]
I've been using gemini with the gemini-browserstack library, and I've noticed that due to some kind of latency issue gemini fails to resize the browser window in time for the screenshot to be taken, resulting in the window size being out by anywhere between 5 and 50 pixels. This ends up significantly breaking the tests.

Is there any way to get gemini to wait for the rendering to finish after the window is resized before taking a screenshot?

**Comment by SwinX** [comment]
@lyptt on which browsers are you experience this issues?

**Comment by SwinX** [comment]
Closed due to issue reporter inactivity: https://github.com/gemini-testing/gemini/blob/master/CONTRIBUTING.md#issues-reporting
