### ISSUE TITLE
Why Gemini was removed from en.bem.info

### ISSUE THREAD

**Issue by vitman** [gemini-testing/gemini#343]
..and docs removed from repo. Whether gemini dying or documentation just going to be updated?

**Comment by SevInf** [comment]
No one is dying (except for the RU docs since it was tedious to maintain both, se #337).
gemini have nothing to do with BEM methodology, so bem.info was not the best place to keep a documentation for it.
We'll have our own site hosted on github pages, until then you can read the docs on github
