### ISSUE TITLE
2.0.3 Error: read ECONNRESET

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#353]
After upgrading from 1.1.6 -> 2.0.3 I started to run into an issue where tests at the end of a run are failing, I run around 77 tests in total, and the last 9 - 10 are failing.  If I just run those 10 by themselves that are failing they are fine.  If I go back to 1.1.6, everything is back to normal
During the test I see this for the out of the individual suite
Cannot launch browser PhantomJS:
[init({"browserName":"phantomjs","screenResolution":"1280x1024"})] read ECONNRESET

I get this error message at the end.
Critical error in PhantomJS:
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:544:26)

**Comment by SwinX** [comment]
Hi @vpatton, thank you for your report.
Can you please provide your .gemini.yml ? Also it would be great to have some details about testing environment.

**Comment by vpatton** [comment]
Nevermind I guess? I ran the tests again today (Had to handle a separate fire) and it worked, there were no code changes, so i guess I ran something wrong, haven't had that error again

**Comment by SwinX** [comment]
:ok: , closing issue then.
