### ISSUE TITLE
`<style>` elements cause coverage report generation to fail

### ISSUE THREAD

**Issue by benedfit** [gemini-testing/gemini#367]
I believe the coverage generator is falling over at https://github.com/gemini-testing/gemini/blob/master/lib/coverage.js#L34 when the page contains a `<style>` element

**Comment by SwinX** [comment]
@benedfit is this still actual or your PR fixed this?

**Comment by benedfit** [comment]
This is still the case, I haven't got around to working on a fix for this

**Comment by sipayRT** [comment]
Can you provide example for your case? I can't reproduce it

**Comment by benedfit** [comment]
@sipayRT In my case I am integrating Typekit, which adds a `<style>` tag dynamically via it's JavaScript snippet

**Comment by sipayRT** [comment]
can you add some example of the page?
