### ISSUE TITLE
Gemini fails to generate report

### ISSUE THREAD

**Issue by geitsund** [gemini-testing/gemini#368]
Gemini fails to generate test report when none of the suites uses a capture stateName 'default'.

I have a number of test suites with captures capture stateNames 'desktop', 'mobile', 'tablet vertical' and 'tablet horizontal'. If i run these tests the gemini-report folder only contains the screenshots folder. If i change capture stateName from 'desktop' to 'default' the report html is generated.

`gemini.suite('02 Gateway - Privacy Statement', function(suite) {`
`suite`
        `.setUrl('/PrivacyStatement')`
        `.setCaptureElements(captureElement)`
        `.capture('mobile', function(actions, find) {`
         `actions.setWindowSize(screenSizes.mobile.width, screenSizes.mobile.height);`
        `})`
        `.capture('tablet portrait', function(actions, find) {`
            `actions.setWindowSize(screenSizes.tabletPortrait.width, screenSizes.tabletPortrait.height);`
       `})`
        `.capture('tablet landscape', function(actions, find) {`
            `actions.setWindowSize(screenSizes.tabletLandscape.width,``screenSizes.tabletLandscape.height);`
`})`
 `.capture('desktop', function(actions, find) {`
  `actions.setWindowSize(screenSizes.desktop.width, screenSizes.desktop.height);`
 `});`
`});`

**Comment by SwinX** [comment]
@geitsund thank you for the report.
Does gemini print any errors? It would be nice to have more details

**Comment by geitsund** [comment]
@SwinX No, it just ends the test run. Gemini-Report folder with test screen caps in the images folder are generated, but no html, css files etc.

I have also recreated the bug when the capture stateName is 'default'.

It looks like the test ends before the report has time to generate. If i add a test suite at the end of my file with a timeout it manages to create the report most of the time.

Let me know if you need more input.

**Comment by geitsund** [comment]
Looks like the report generation fail is due to the imagesReady promise not being resolved or rejected.
view.createHtml and view.save are never being executed.

Seems like changing line 110 in /lib/reporters/html/index.js from
queue.then(imagesReady.resolve, imagesReady.reject); to
queue.then(imagesReady.resolve(), imagesReady.reject()); solved the problem.

**Comment by SwinX** [comment]
@geitsund seems lines you point at are not causing issue cause queue has to call imagesReady resolve\reject handler when it would be ready. In proposed patch we're calling it manually, which is not what we really want.
Anyway this is a good point, problem seems to be somewhere there

**Comment by sipayRT** [comment]
fixed in v4.13.3
