### ISSUE TITLE
Gemini not ignoring pseudo selectors

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#386]
It looks like `ignoreElements` does not work for pseudo selectors, like `.button:before`. Bug of feature?

**Comment by sipayRT** [comment]
it's because of troubles to get coordinates of the pseudo elements from js. Gemini needs coordinates to paint over ignored elements on the screen

**Comment by varya** [comment]
The solution (based on the next issue answer)

```
+        actions.executeJS(function(window) {
+          var sheet = window.document.styleSheets[0];
+          sheet.addRule('.button-spinner:before', 'animation: none !important');
+          sheet.addRule('.button-spinner:before', '-webkit-animation: none !important');
+        });
```
