### ISSUE TITLE
How to I ignore elements with transitions?

### ISSUE THREAD

**Issue by varya** [gemini-testing/gemini#387]
What is the best way to ignore an element which has different size when taking reference screenshot and later when testing?

For example, I have a button with a progress bar. Using `ignoreElements` does not help because this makes my progress bar black, but it still can be of different size and give a visual difference when comparing:

![chrome](https://cloud.githubusercontent.com/assets/27215/13638258/24973b36-e614-11e5-859b-6d068dcfa843.png)

I may make the test passed with `setTolerance` but this solution does not look elegant. Is there any other ideas? Like providing additional CSS in the suite on fly which would overwrite such transitions. How can I provide such additional CSS? Or could you share other ideas which may help please?

**Comment by sipayRT** [comment]
you should switch off `transition`. For example:

```
* {
    animation: none !important;
    transition: none !important;
}
```

Or add this CSS just for your element. You can do it using `executeJS` method.

**Comment by SwinX** [comment]
@varya have you tried this? Also you may use `actions.wait`, but this also obviously a kludge and @sipayRT solution looks better.

**Comment by varya** [comment]
This works, thank you. I'm adding additional CSS in `executJS` like it is written here https://davidwalsh.name/add-rules-stylesheets
I believe that this is more elegant that using `wait`.
Thanks for the comments.
