### ISSUE TITLE
Proxy Settings for Browsers

### ISSUE THREAD

**Issue by Purus** [gemini-testing/gemini#389]
We are behind a corporate firewall and browsers use proxy to connect to Internet.

In selenium we generally use profiles and capabilities to setup proxy details.

I see there are options in Gemini to setup capabilities. But there are no clear document on setting up proxy details.

Any suggestions?

**Comment by SwinX** [comment]
@Purus there is no proxy support in gemini. 
As a suggestion I may propose this [plugin](https://github.com/gemini-testing/gemini-tunnel). It establishes ssh connection to some host in a way that all requests for this host:port will be redirected to localhost:localport. Hope this may help.

**Comment by SwinX** [comment]
Closing due to no reaction from contributor: https://github.com/gemini-testing/gemini/blob/master/CONTRIBUTING.md
