### ISSUE TITLE
Transpile code and tests using babel order to have possibility to write code and tests in ES6

### ISSUE THREAD

**Issue by SwinX** [gemini-testing/gemini#400]

**Comment by j0tunn** [comment]
Maybe we just remove support <node@4.x some day?

**Comment by SevInf** [comment]
Or not wait for some bright future which never happens and use current standard features now.
Even Node 5.x does not supports few ES2015 such useful features as default parameters and destructuring assignment and modules. When we'll drop 0.10 we can just switch [preset](https://www.npmjs.com/package/babel-preset-es2015-node4) and don't compile what is already supported.
Debugging is not such a big problem, as commonly described. `node-inspector` and WebStorm can read sourcemaps, [this](https://github.com/evanw/node-source-map-support) package will give you proper stacktraces in terminal and `console.log` and `debugger` statements won't stop working in transpiled code.

**Comment by SevInf** [comment]
And we don't even need to run anything during development.
We can do somthing like this in `bin/gemini`:

```js
if (exists('../src')) {
    // during development we will compile ES6 to ES5 on the fly with require hook.
    require('babel-register')();
    cli = require('./src/cli');
} else {
   // in published build we use pre-compiled code
    cli = require('./lib/cli');
}
```

provided that we have compile step in prepublish script and `src` directory in `.npmignore`

**Comment by SwinX** [comment]
I agree with @SevInf that we have no point in waiting for node.js support of new language features:

- For core development we have no overhead related to build time becase this must be done once before publish. For debugging we may use source maps which are widely supported
- For tests code there are several options: we may force users to compile tests by themselves, compile tests all the time or compile if user will specify some compiler. 3rd path looks best because it requires 1 line integration and will be backwards-copatible with older tests.

In general further development with ES6 looks logical from point of using most advanced language features. This may simplify our code base (for instance look at [async/await](https://jakearchibald.com/2014/es7-async-functions/) functions) so support of existing features and implementation new will be much simpler.

**Comment by SwinX** [comment]
As from previous discussions seems everyone agree with ES6 and babel.
@SevInf can you setup it ?

**Comment by sipayRT** [comment]
closed due to inactivity. Now we remove support < node@4.x
