### ISSUE TITLE
Feature: Add xml or JSON report

### ISSUE THREAD

**Issue by vpatton** [gemini-testing/gemini#403]
It would be great to have an output in xml or even JSON report so that it can be used with something like Jenkins.  I tried to do something myself, but I'm running into problems adding it to the reports directory in gemini.

**Comment by vpatton** [comment]
I added something to the getResult in the test-counter.js to get it to output an xml file, but its kind of hacky

**Comment by SwinX** [comment]
@vpatton you may try to do it with a plugin. As example see [gemini-teamcity-reporter](https://github.com/gemini-testing/gemini-teamcity)

**Comment by alexpts** [comment]
+ xUnit (xml)

**Comment by sipayRT** [comment]
This issue will be closed due to @SwinX advice
