### ISSUE TITLE
Add to meta-information to the full path of the page

### ISSUE THREAD

**Issue by xaircore** [gemini-testing/gemini#489]
Add to meta-information to the full path of the page on which pass the tests. Make a display of the path by reference to the possibility of opening a new tab when you click on it

**Comment by sipayRT** [comment]
In case when you use gemini-tunnel plugin your rootUrl will be changed to the tunnel host. For example, your url will be changed from localhost:8989/test.html to the http://my-tunnel.com:1234/test.html. So at the report it will be wrong url.
But you can add any information to metaInfo from your plugin by extending `state.metaInfo` object

**Comment by xaircore** [comment]
@sipayRT Ok. How i can add my own metainfo in report without using plugin? And where to find documentation or example about adding metainfo from plug-in by extending state.metaInfo?

**Comment by sipayRT** [comment]
> How i can add my own metainfo in report without using plugin?

you can't do it without plugin. 

> where to find documentation or example about adding metainfo

Documentation not ready yet. Example:

```
gemini.on('startRunner', function(runner) {
    runner.on('endTest', function (data) {
        var state = data.state;
        state.metaInfo.someOption = 'http://some.com/' + state.metaInfo.url;
    });
});
```

**Comment by xaircore** [comment]
@sipayRT Thanks for help
