### ISSUE TITLE
Long pages crop in Chrome and Opera

### ISSUE THREAD

**Issue by enotramone** [gemini-testing/gemini#49]
Tested on a few pages with long layout. Took for example: https://github.com/bem/gemini
Specified CSS selector covers full page (body element also fits).
Simple test:
```
var gemini = require('gemini');
gemini.suite('crop', function(suite) {
    suite
        .setUrl('/bem/gemini')
        .setCaptureElements('.wrapper')
        .capture('initial');
});
```
Use Selenium Grid with PhantomJS 1.1.1, Opera 12.16, Firefox 25.0, Chrome 33, IE 9 and IE10.

On the resulting screenshots the Chrome one was cropped by the monitor dimensions and Opera as well. All other browsers show expected results.

**Comment by SevInf** [comment]
Driver issue, we can't do much about it.
