### ISSUE TITLE
Add possibility to define custom configuration we can use in the test suite

### ISSUE THREAD

**Issue by fsevestre** [gemini-testing/gemini#498]
I haven't seen an other issue on the subject (or in the doc), I hope I don't create a duplicate.

I would like to know if it is possible to define custom configuration we can use in the test suite.
For example, when I test multiple pages protected by a login/password form I do something like this:

``` javascript
...
    suite.setUrl('/admin')
        .before(function(actions, find) {
            actions.sendKeys(find('#username'), 'my_admin_username');
            actions.sendKeys(find('#password'), 'my_admin_password');
            actions.click('#submit-button');
        })
...
```

When we have to test multiple actions/pages with different users using specific roles for example, I don't want to repeat the login/password every time (and if the login/password changes, it would be easier to change it in one place only).

Is this something possible?

**Comment by sipayRT** [comment]
hi.
It's not possible now, but we already have an issue about custom commands - https://github.com/gemini-testing/gemini/issues/197.
At this moment you can move your `login` function to some helper and require it for each test-file.
