### ISSUE TITLE
Add command to CLI run only failed tests

### ISSUE THREAD

**Issue by xaircore** [gemini-testing/gemini#505]
Sometimes you need to run, not all tests, only those that have failed. It would be very easy to run only the failed tests, not all of which are

**Comment by xaircore** [comment]
@SwinX @SevInf Can we do this behavior?

**Comment by SwinX** [comment]
@xaircore What do you mean by failed tests? If tests failed on previous run then this is not a good idea. Implementation this thing in core will lead to some kind of state in gemini which will break test runner concept. 

Alternatively you may use [gemini-gui](https://github.com/gemini-testing/gemini-gui), where you're able to rerun failed tests. Or you may write gemini plugin which will dump failed test and on next run check dump and filter tests before run.

**Comment by xaircore** [comment]
@SwinX How i can write own plugin for this behavior? Is there any documentation for this?

**Comment by SwinX** [comment]
You can find plugin documentation [here](https://github.com/gemini-testing/gemini/blob/master/doc/plugins.md) and programmatic API documentation [here](https://github.com/gemini-testing/gemini/blob/master/doc/programmatic-api.md).
