### ISSUE TITLE
Shorten require paths in tests

### ISSUE THREAD

**Issue by j0tunn** [gemini-testing/gemini#509]
In our tests we have bunch of requires like:
```js
const MetaScreenUpdater = require('../../../../../lib/state-processor/capture-processor/screen-updater/meta-screen-updater');
const temp = require('../../../../../lib/temp');
```

It would be nice to write require relative to project root:
```js
const MetaScreenUpdater = require('lib/state-processor/capture-processor/screen-updater/meta-screen-updater');
const temp = require('lib/temp');
```

For that we can use some module like `app-module-path`: https://gist.github.com/branneman/8048520#3-the-module

**Comment by sipayRT** [comment]
https://github.com/gemini-testing/gemini/pull/512
