### ISSUE TITLE
Add option ignoreCaret to config

### ISSUE THREAD

**Issue by xaircore** [gemini-testing/gemini#527]
Sometimes when testing input field tests fall due until the cursor appears. In the look-same library there is an option to ignoreCaret to solve this problem. I would like to be able to set this option by default via the configuration file

**Comment by tormozz48** [comment]
@xaircore 

Thank you for this question. But as you can see [here](https://github.com/gemini-testing/gemini/blob/master/lib/browser/client-scripts/gemini.js#L74) and [here](https://github.com/gemini-testing/gemini/blob/master/lib/browser/client-scripts/gemini.js#L231) there no necessity to have this option in configuration because ` ignoreCaret` is set automatically depending on active page element.

**Comment by xaircore** [comment]
@tormozz48 But my test fail [report](http://shot.qip.ru/00DuQd-4oZhWgttp/). There is my [config](https://gist.github.com/xaircore/854acc875ebb9e9938847423be8c55a3)

**Comment by tormozz48** [comment]
@xaircore Please show code of your test. Are you sure that you have latest version of gemini and looks-same plugin? Recently we have fixed some bug with caret for devices with pixeRatio > 1

**Comment by xaircore** [comment]
@tormozz48 Sorry, I forgot to mention that I use an older version, to be exact it - 1.1.6. In the nearest days I plan to go to 4.4.1. If you have the same problem, I'll let you know

**Comment by xaircore** [comment]
@tormozz48 Now I'm using version 4.10, but the problem remained with the caret. See my [screenshot ](http://shot.qip.ru/00DuQd-4oZhWgtTM/)

**Comment by tormozz48** [comment]
//cc @sipayRT @j0tunn

**Comment by j0tunn** [comment]
As I can see there are no problems with caret.
`gemini` ignores caret if it is the only diff on page. But you have other diffs:
![](https://yadi.sk/i/vGiqcyuJvn3us_XL.png)
so `gemini` shows the whole diff (including the caret)

**Comment by j0tunn** [comment]
I suggest you to change the diff colour to make it more visible

**Comment by xaircore** [comment]
@j0tunn Thanks for the explanation the situation
