### ISSUE TITLE
Out of bounds at certain window sizes

### ISSUE THREAD

**Issue by nicrodgers** [gemini-testing/gemini#543]
Why do some window sizes report 'out of bounds' when running the update command? 

I have compositeImage: true in my conf file, so I would expect that it would work in any window size.

For example, I am trying to capture my footer element.

Gemini works at these window sizes:
320x640
600x800
960x1024

But fails 'out of bounds' at:
480x800
768x1024

Is that a bug, or am I misunderstanding how it should work?

**Comment by sipayRT** [comment]
hi. can you provide more info about your environment? Which browser do you use for testing?

**Comment by nicrodgers** [comment]
Hi sipayRT, thanks for helping out. This is using Selenium with Firefox.

**Comment by sipayRT** [comment]
hi. sorry for delay. we trying to reproduce this bug. Can you provide your page for testing? Maybe it connected with your page layout

**Comment by nicrodgers** [comment]
Hi sipayRT, no problem for the delay, thanks for coming back to me.

Here's a cut-down version of the config file we are using:
[example-conf.zip](https://github.com/gemini-testing/gemini/files/461238/example-conf.zip)

selenium-server-standalone-2.46.0
Firefox 38

I've also attached the console output from when we run gemini, you can see we get two errors on the footer:
[console.txt](https://github.com/gemini-testing/gemini/files/461246/console.txt)

**Comment by eGavr** [comment]
@nicrodgers 

Url `https://consultations.gov.wales/` has stopped to response. I've tried it several days ago and everything was Ok, but know I can not reproduce your test cases :(

**Comment by nicrodgers** [comment]
hi @eGavr, I have sent you an email to try and get you access back to the site. Let me know if you don't receive the email. thanks!

**Comment by eGavr** [comment]
@nicrodgers 

Is it possible that your site fails because of many requests which I send from gemini tests ? :)

**Comment by eGavr** [comment]
@nicrodgers 

Try branch from https://github.com/gemini-testing/gemini/pull/592, please, if everything is Ok I will bump a patch.

**Comment by nicrodgers** [comment]
works great now, thank you!
