### ISSUE TITLE
Calculate every time in actions methods WebElement

### ISSUE THREAD

**Issue by xaircore** [gemini-testing/gemini#551]
Calculate every time in actions methods webelement passed to find callback. This is to ensure that if an item is missing from the DOM but then came back with not falling with StaleElementReference 

`Error: [moveTo({"ELEMENT":"87"})] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: stale element reference: element is not attached to the page document`

Output of `gemini --version`:

0.13.4

Test source code:

```	
    gemini.suite('single', function (test) {

        test.setUrl('/regression_dropdown_list_online_6.html').setCaptureElements('.capture')

            .before(function (actions, find) {
                actions.waitForElementToShow('[name="DropdownList 1"]', 40000);
                this.list = find('[name="DropdownList 1"]');
				this.title = find('[name="DropdownList 1"] .controls-DropdownList__text');
				this.item4 = find('.controls-DropdownList__item[data-id="4"]');
				actions.waitForElementToShow('[sbisname="TextBox 1"]', 40000);
                this.input = find('[sbisname="TextBox 1"] input');
            })

            .capture('plain', function (actions) {
                actions.click(this.input);
            })

            .capture('hovered', function (actions) {
                actions.mouseMove(this.title);
            })

            .capture('opened', function (actions) {
                actions.click(this.title);
				actions.waitForElementToShow('.controls-DropdownList__item[data-id="4"]', 1000);
				actions.mouseMove(this.input);
            })
			
			.capture('hovered_item', function (actions) {
                actions.mouseMove(this.item4);
            })
			
			.capture('selected', function (actions) {
                actions.click(this.item4);
				actions.mouseMove(this.input);
            })
			
			.capture('opened_again', function (actions) {
                actions.click(this.title);
				actions.waitForElementToShow('.controls-DropdownList__item[data-id="3"]', 1000);
				actions.mouseMove(this.input);
            })
			
			.capture('disabled', function (actions) {
				actions.click(this.input);
                actions.executeJS(function (window) {
                    window.$ws.single.ControlStorage.getByName('DropdownList 1').setEnabled(false);
                });
            })
    });
```

**Comment by SevInf** [comment]
`find` function designed specifically so you can cache its result and avoid further lookups. If you don't want this behaviour, you can just pass a selector as an argument for an action:

```js
actions.mouseMove('.my-element')
```

**Comment by xaircore** [comment]
@SevInf But what if I do many time to interact with the variable again. Each time the write selector? And if he then changed the rules in all places?

**Comment by SevInf** [comment]
@xaircore nodody is stopping you from doing this:

```js
.before(function() {
    this.myElement = '.my-selector';
})
.capture('state', function(actions) {
    actions.click(this.myElement);
})
```

**Comment by xaircore** [comment]
@SevInf Yes, but why then need find function?

**Comment by SevInf** [comment]
@xaircore when you are doing `.moveTo('.my-selector').click('.my-selector')`, two http requests to selenium server are issued:
1. Searching for the element, corresponding to `.my-selector`.
2. Moving the pointer to that element.
3. Searching for the element, corresponding to `.my-selector`.
4. Clicking on that element.

So, the search is actually performed 2 times. This is fine if the element, corresponding to the selector is somehow different after the first action. But in most cases, it is the same element and you can avoid sending the second search request. Here `find` function comes into play. So, if you are doing this:

```js
var myElement = find('.my-selector');
actions.moveTo(myElement).click(myElement);
```

the actual sequence of http requests will be:

1. Searching for the element, corresponding to `.my-selector`.
2. Moving the pointer to that element.
3. Clicking on that element.

And this the only purpose of the find function. And it actually [documented](https://github.com/gemini-testing/gemini/blob/master/doc/tests.md#suite-builder-methods)

**Comment by xaircore** [comment]
@SevInf Thanks for the help

**Comment by xaircore** [comment]
@SevInf Forgive me for asking it. But what is winning when using the cached WebElement instead of calculating the WebElement each time. How it affects the performance of the tests, and where the bottleneck computation WebElement each time

**Comment by SevInf** [comment]
@xaircore searching for element issues a separate http request to Selenium server. If you are running it locally it is not big deal, but if your server is remote it can take significant time. This is especially true for cloud services, such as SauceLabs and BrowserStack.
