### ISSUE TITLE
Add possibility to pass headers while opening url

### ISSUE THREAD

**Issue by Demven** [gemini-testing/gemini#552]
To open a page from our qa-server I have to pass special headers, but I couldn't find how to do it using Gemini. 
Currently we use Phantomcss + Casper and there it is possible, but we want to migrate to Gemini to be able to test in all browsers.

How to pass headers? Can you implement such functionality?

**Comment by sipayRT** [comment]
hi. gemini can't change headers for the page. but you can try to do it with [browsermob-proxy](https://github.com/lightbody/browsermob-proxy)

**Comment by Demven** [comment]
@sipayRT Thanks for your solution
