### ISSUE TITLE
Remove element from page or modify executeJS() function

### ISSUE THREAD

**Issue by Demven** [gemini-testing/gemini#553]
Can you implement additional action to make it possible to remove DOM elements before capture? I need to capture some components that are covered by another and need to remove it from page. I would use executeJS() to do it, but I can't pass arguments to that function, it can take only window object. So another solution would be to let the executeJS() function take parameters like Casper does:
casper.evaluate((sel) => {
      const elementToRemove = document.querySelector(sel);
      elementToRemove.parentNode.removeChild(elementToRemove);
}, selector);

Is it possible to extend  executeJS() functionality to be able to pass there some arguments or implement special action 'removeElement()'?

**Comment by sipayRT** [comment]
hi. what about helper?

```
var format = require('util').format;

/**
 * actions.executeJS(executeJsInspector(function(window) {
 *     var input = window.document.querySelector(selector)
 *         input.value = 'ololo';
 * }, { selector: '.input .input__control' }));
 */
exports.executeJsInjector = function(fn, vars) {
    var varsToExport = Object.keys(vars)
        .map(function(v) {
            return format('var %s = "%s";', v, vars[v]);
        })
        .join('\n');

    return new Function([
        varsToExport,
        format('(%s)(window)', fn.toString())
    ].join('\n'));
};
```

**Comment by Demven** [comment]
@sipayRT Thanks for your solution, will try it.
