### ISSUE TITLE
v.5 Breaking changes

### ISSUE THREAD

**Issue by DudaGod** [gemini-testing/gemini#555]
- [x] Remove CAPTURE event. UPDATE_RESULT - it's new event instead CAPTURE. https://github.com/gemini-testing/gemini/pull/837

**Comment by rostik404** [comment]
* Запретить прокидывать  `grep` в функцию `readTest` (`lib/gemini.js`)

**Comment by DudaGod** [comment]
* Remove END_TEST event. TEST_RESULT - it's new event instead END_TEST.

**Comment by DudaGod** [comment]
* Remove BEGIN and END events.

**Comment by SevInf** [comment]
Remove `q-bluebird` library, return bluebird promises from public API methods.

**Comment by eGavr** [comment]
Remove WARNING event

**Comment by eGavr** [comment]
Remove `BEGIN_SESSION` and `END_SESSION` events.

**Comment by j0tunn** [comment]
Rename events:
- `START_BROWSER` -> `SESSION_START`
- `STOP_BROWSER` -> `SESSION_END`
Those events actually indicate when browser *session* starts and ends. There are lots of sessions during run

**Comment by eGavr** [comment]
Move `root.system.plugins` to `root.plugins`

**Comment by eGavr** [comment]
`rootUrl` –> `baseUrl`

**Comment by SevInf** [comment]
>Move root.system.plugins to root.plugins
The original idea of the current structure was:
- anything at top level can be overriden at browser level
- anything under `system` can be specified only once and can not be overriden.

By this definition, plugins fall into second category. Also, this distinction is [explicitly stated in current documentation](https://github.com/gemini-testing/gemini/blob/master/doc/config.md#browsers-settings)

**Comment by eGavr** [comment]
Sooooo.  We need `sets` option and so on.. move to system ?

**Comment by sipayRT** [comment]
`ignoreElements` method:
ignore all matched elements by default without any helpers — https://github.com/gemini-testing/gemini/pull/692

**Comment by levonet** [comment]
Запускать тесты по команде `gemini`, **со временем** оторвать `gemini test`.

**Comment by DudaGod** [comment]
* Supports only Node v6 (LTS) and greater.
* Update https://github.com/admc/wd to last version.

**Comment by j0tunn** [comment]
Все остальное унес в https://github.com/gemini-testing/gemini/issues/844
