### ISSUE TITLE
Gemini captures incorrect area sometimes (but of the same size)

### ISSUE THREAD

**Issue by Demven** [gemini-testing/gemini#581]
Hello, I have a strange problem with capturing my components: sometimes gemini saves screenshot with another part of a page, sometimes there is only a part of a desired component and often it's just a top of the page. But each time the size of screenshot is completely the same as the component I want to capture. And what's important - it occurs arbitrarily: this time failed that component on firefox, next time it's another component but in chrome, or in both browsers. So each test-launch fails for this reason on arbitrary components.

For example here are two failed cases:
1. Need to capture this component with image and caption, but instead it takes screenshot of the area above the picture, like it didn't scroll to the required position before capturing.
<img src="https://s10.postimg.org/nc8b1xah5/screenshot.png" />
2. Here we need to capture the image with description inside of an article, but gemini just captured the top of the page with navigation.
<img src="https://s9.postimg.org/jbe0jj15r/screenshot1.png" />

Contents of `.gemini.yml` file:
```yaml
rootUrl: http://....
gridUrl: http://....
compositeImage: true
screenshotsDir: 'screens/desktop'
windowSize: 1280x1024

system:
  projectRoot: ../phantomcss
  debug: false

browsers:
  chrome-latest:
    desiredCapabilities:
      browserName: chrome
  firefox-latest:
    desiredCapabilities:
      browserName: firefox
```yaml

**Comment by Demven** [comment]
I have a suspicion that this issue caused by the loaded ads: when ad appears - page expand, and content can move to a different position so Gemini captures incorrect area.

**Comment by sipayRT** [comment]
so you need to disable any ads for your page for testing

**Comment by Demven** [comment]
Yes, it's the same problem as https://github.com/gemini-testing/gemini/issues/594
