### ISSUE TITLE
gemini показывает зелёный экран и не запускает тесты, ETIMEDOUT.

### ISSUE THREAD

**Issue by AEIlin** [gemini-testing/gemini#582]
Есть компьютер на Ubuntu. На нём есть nginx с тестовыми примерами для gemini. Поднят тутже selenium hub. К hub-у подключён node с виртуалки. Виртуалка - virtualBox - win7 - ie11.
Запускаю gemini тест - на виртуалке открывается окно браузера - с светло зелёным экраном. Как я понял - это цвет какого-то джеминевского калибратора. Но дальше тесты не запускаются. Через какое-то время Gemini падает с ошибкой, что не удалось запустить ie11 - ETIMEDOUT.
gemini.conf http://pastebin.com/7meB32Wt
тест http://pastebin.com/CNW10GyS
конфигурация Selenium node http://pastebin.com/tR6yDxcn
вресия selenium 2.53.1
gemini 4.4.1, 4.8.0, 4.9.0

Пробовал делать скриншоты, используя nightwatch.js и там всё проходило отлично.

**Comment by sergeypchelkin** [comment]
у меня заработало, после того как выставил настройки в браузере ie11 http://www.michael-whelan.net/selenium-webdriver-and-ie11/

**Comment by AEIlin** [comment]
Все эти настройки конечно же стоят.
Данную конфигурацию я проверял через nightwatch.js - всё работало. Кстати решил использовать его для css-тестов :) Пришлось немного самому заморочиться со сравниванием, но это не очень сложно.

**Comment by levonet** [comment]
Закрьіваю по причине даности.
