### ISSUE TITLE
Migrate away from q and q-io

### ISSUE THREAD

**Issue by SevInf** [gemini-testing/gemini#588]
Both `q` and `q-io` does not look actively maintained.

Last version of `q` was published a year ago.
Last version of `q-io` is 9 month old, but it breaks ES6 array methods and to workaround it, we should use `q-io@2.x` which was last published 2 years ago.

Meanwhile, [`bluebird`](http://bluebirdjs.com/) is actively maintained, significanly [faster](http://bluebirdjs.com/docs/benchmarks.html) and has pretty staritforward [migration guide](http://bluebirdjs.com/docs/coming-from-other-libraries.html#coming-from-q). It is also much more [feature-rich](http://bluebirdjs.com/docs/api-reference.html) and probably will allow us to get rid of `q-promise-utils`.

As for `q-io`, a lot of our use-cases can be replaced by built-in `fs` module + `Bluebird.promisifyAll`. The rest is available in [`fs-extra`](https://www.npmjs.com/package/fs-extra) and [`glob`](https://www.npmjs.com/package/glob).

TODO:
- [X] Replace `Q` in `gemini` 
- [x] Replace `q-io` in `gemini`
- [x] Migrate `gemini-gui`
- [ ] Migrate `gemini-coverage`
- [ ] Migrate `glob-extra`
- [ ] Create `BluebirdEmitter`
- [ ] Create `bluebird-promise-utils`

**Comment by zxqfox** [comment]
https://github.com/normalize/mz ?

**Comment by sipayRT** [comment]
migration to bluebird looks simple

**Comment by tormozz48** [comment]
A agree with @SevInf. bluebird became a most relevant third-party promise library

**Comment by sipayRT** [comment]
@SevInf what about backward compatibility (I mean our plugins that also uses `q`)? Can you investigate it?

**Comment by SevInf** [comment]
@sipayRT thats a good point. We do not expose `q` to the plugins directly and every plugin that needs it has its own dependency on it.
But programmatic API methods `readTests`/`test`/`update` return q promise, so someone may rely on q-specific methods and this is indeed a breaking change.

I see 2 solutions:
1. Do the migration and release it as 5.0
2. Migrate to `bluebird` internally, still return `q` promise from public API methods (`q(someOtherPromise)` will cast any promise to `q`).

Unless we have 5.0 already on the horzion, I personally prefer the second one.

**Comment by SevInf** [comment]
Just found out about another option, which actually looks the best right now [`bluebird-q`](https://github.com/petkaantonov/bluebird-q).
Basically, it is bluebird with Q interface. So, this should take care of all `q` migration part, we just need to do something about `q-io`.

`mz` can be an option, but in lacks `glob`, `makeTree`, `removeTree` and `copyTree` support.

**Comment by Dmitriy-kiselyov** [comment]
Both gemini and gemini-core do not use `q` and `q-io` libraries anymore
