### ISSUE TITLE
How Should I <select> <option>s?

### ISSUE THREAD

**Issue by nathagey** [gemini-testing/gemini#593]
Is there documentation that would show me how to select an option from a select menu?

`
<select id="select-menu">
<option value="cool">Cool</option>
</select>
`

**Comment by sipayRT** [comment]
hi.
You can click the select and select option (another) click:

```
actions
    .click('#select-menu')
    .click(('#select-menu option:first-child)'));
```

Also you can do it with `executeJS` method:

```
actions.executeJS(function(window) {
    var select = window.document.getElementById('select-menu');
    select.value = 'cool';
});
```

**Comment by nathagey** [comment]
Both worked. Thanks!
