### ISSUE TITLE
Strange issue with image offset by 1px

### ISSUE THREAD

**Issue by Demven** [gemini-testing/gemini#594]
I often have a strange issue with offset by 1px like this:

<img src="https://i.gyazo.com/31478b612ffbcf174c4b4799b4641bf3.png" />

It happens on random tests and primarily in Chrome.
Can I set somehow the precision of image comparison so that it would be possible to ignore such offset?

**Comment by sipayRT** [comment]
hi. It happens because of block position changing in Chrome.  It render page with those diffs. Unfortunately you can't prevent it. But you can switch on retries to hide this problem

**Comment by Demven** [comment]
@sipayRT Thanks for your answer, I used script injecting to remove all ads from the page and it helped.
