### ISSUE TITLE
How to test on Android in Chrome using SauceLabs?

### ISSUE THREAD

**Issue by Demven** [gemini-testing/gemini#599]
Could you please give a working example of a configuration to run tests on Android devices (preferably in Chrome)?
I tried all parameters from SauceLabs docs but it doesn't work :(
And currently it's not possible to run tests on iOS, is it?

**Comment by sipayRT** [comment]
hi. android5 config for sauceLabs:

```js
'android5': {
    browserName: 'Browser',
    appiumVersion: '1.5.2',
    deviceName: 'Android Emulator',
    deviceOrientation: 'portrait',
    platformVersion: '5.0',
    platformName: 'Android'
}
```

**Comment by sipayRT** [comment]
for IOS we have some problems with coverage. So IOS doesn't support yet

**Comment by Demven** [comment]
@sipayRT thank you!
