### ISSUE TITLE
Release process: have a testing period for next major and minor releases

### ISSUE THREAD

**Issue by SevInf** [gemini-testing/gemini#609]
Make `@latest` releases more stable by adopting something to [npm](https://github.com/npm/npm/wiki/CLI-Team-Process#the-npm-release-train) release process.

TL;DR: new version does not receives `latest` tag for some fixed time, until it battle-tested.  This allows to:
1. Still have a release with defined scope, which can be installed manually.
2. Have some testing period before declaring the release stable.

@j0tunn @DudaGod @sipayRT @eGavr

**Comment by j0tunn** [comment]
Can you give more details? I don't quite understand how it works and what should we do.

**Comment by SevInf** [comment]
The main idea is to have some grace period before next release is declared stable. This should help  to reduce the number releases, which break not used by Yandex functionality (there were quite a few such releases lately).
The link in the description describes the process, npm uses for its CLI, which I think might be useful for gemini. Basically the whole idea boils down to delaying updating `latest` tag on npm package until some fixed time passed. For example, when we publish `4.12.0`:

- First publish is done with `npm publish --tag next`. This will allow version to be installed explicitly, but prevent automatic updates for ranges, like `^4.0.0`. But if you want to have automatic updates to such version, you can still depend on `gemini@next`.
- For some time (I would suggest a week) things stay stay that way. If critical bug is discovered in that time, we publish `4.12.1`, `4.12.2` and so on as the `next` tag.
- After grace period ended, we add `latest` tag to `4.12.x` and enable automatic updates for semver ranges.

**Comment by sipayRT** [comment]
so after several failures user will get update from 4.12.1 to 4.12.7? and tags 4.12.2-4.12.6 will be ignored?

**Comment by SevInf** [comment]
@sipayRT I would propose using it only for minor versions, since bug fixes should be delivered ASAP. So, in this case it will be more like:
* if you have dependency on `gemini@^4.11.0` it will update from `4.11.3` to `4.12.6` without going throught presumably broken `4.12.0`-`4.12.6`
* Until 4.12 declared stable, you can install it explicitly with `gemini@4.12.1`, `gemini@4.12.2` or `gemini@^4.12.0` if you want autoupdates.
* If you want to always live on a bleeding edge, use depend on `gemini@next`.

**Comment by sipayRT** [comment]
@SevInf so can I close this issue?

**Comment by Dmitriy-kiselyov** [comment]
This functionality is implemented
