### ISSUE TITLE
Implement ability to create Gemini instance without configuration

### ISSUE THREAD

**Issue by tormozz48** [gemini-testing/gemini#634]
I need to use only some of gemini functionality via gemini API without run tests.
For example I need only to read and parse gemini test files.

Now I must pass minimal configuration object into `Gemini` constructor:

```
const gemini = new Gemini({
       rootUrl: '/',
       system: {projectRoot: process.cwd()}
});
```

But I need not use `rootUrl` param for my task.

Maybe it will possible to make `Gemini` constructor without arguments and set options only before tests running.

**Comment by sipayRT** [comment]
v4.13.0
