### ISSUE TITLE
Тесты работают нестабильно для Edge

### ISSUE THREAD

**Issue by Chudovishee** [gemini-testing/gemini#637]
Я наблюдаю значительные различия в скриншотах от запуска к запуску в одном и том же окружении. Как правило я ловлю различия в тексте и иногда в png картинах. Я пробовал делать скриншоты вручную и сравнивать их, в этом случае я так же получал различия в отображении. Из этого я могу сделать предположение, что виноват больше Edge, чем gemini. Тем не менее я не могу придумать адекватного способа обойти эту проблему. Я пробовал увеличивать `tolerance` в настройках для Edge в диапазоне от стандартного значения и до 30, но в этом случае я только уменьшаю вероятность фейла. Хотелось бы услышать мнение разработчиков по этому поводу, как мне следует правильно обходить эту проблему? Увеличивать дальше `tolerance`? Использовать `setTolerance` для каждого `suite`, подбирая значения для каждого конкретного случая? Или есть более адекватный способ?

Пример сфелившихся тестов.
![gemini](https://cloud.githubusercontent.com/assets/122835/19309519/fe6f31fa-908d-11e6-9fae-837a516c1adf.png)

Версии
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
Output of `gemini --version`: 4.11.3
Output of `node --version`: v4.4.5
Selenium build info: version: '3.0.0-beta3', revision: 'c7b525d'
...

Contents of `.gemini.json` file:

``` json
{
  "rootUrl": "http://127.0.0.1:8080/",
  "gridUrl": "http://localhost:4444/wd/hub",
  "browsers": {
    "chrome_1920x1080": {
      "windowSize": "1920x1080",
      "desiredCapabilities": {
        "browserName": "chrome"
      }
    },
    "edge_1920x1080": {
      "windowSize": "1920x1080",
      "desiredCapabilities": {
        "browserName": "MicrosoftEdge"
      }
    }
  },
  "screenshotsDir": "./data/screens",
  "sessionRequestTimeout": 60000
}
```

Test source code:

``` js
gemini.suite( "topbar", function( suite ){
    suite.setUrl('/')
        .setCaptureElements( "#topbar" )
        .capture( "plain", function( actions ){
            actions.waitForElementToShow( "#topbar" )
        });
});
```

**Comment by sipayRT** [comment]
Привет
Во-первых, у тебя в эталоне обрезана картинка. Во-вторых, тебе в стилях нужно жестко зафиксировать размеры и положение изображения, чтобы исключить возможность смещения иконки во время рендеринга страницы

**Comment by Chudovishee** [comment]
В том то и  фокус, эта иконка не обрезана, там нет overflow: hidden или чего-то еще, что могло бы ее обрезать. Более того, там все зафиксировано в положении. Вот еще пример с текстом. Все совпало идеально, кроме буквы "e". В таком случае даже если была возможность смещаться, то наверное сместился бы весь текст?
![gemini-2](https://cloud.githubusercontent.com/assets/122835/19338420/96fa9e40-9125-11e6-85c5-f93f281fd4a8.png)
![gemini-3](https://cloud.githubusercontent.com/assets/122835/19338423/9980d288-9125-11e6-8830-09090ab8eed7.png)

**Comment by sipayRT** [comment]
> В том то и фокус, эта иконка не обрезана, там нет overflow: hidden или чего-то еще, что могло бы ее обрезать.

ну я выводу делаю из того, что вижу на скриншоте

> Все совпало идеально, кроме буквы "e"

у нас были такие проблемы с рендерингом шрифтов именно в IE. В результате мы отключали в браузере сглаживание шрифтов - помогло

**Comment by sipayRT** [comment]
closed due to inactivity
