### ISSUE TITLE
connect EADDRINUSE

### ISSUE THREAD

**Issue by ghost** [gemini-testing/gemini#646]
When run tests on gemini@4.11.3 part of them failed with error: 
connect EADDRINUSE 

[Screenshot](http://shot.qip.ru/00DuQd-6oZhWgug7/)

What could be the problem? If you need any logs, ready to provide them.

Output of `gemini --version`:

4.11.3

**Comment by xaircore** [comment]
@SevInf @sipayRT @SwinX @j0tunn Are there any suggestions?

**Comment by vincefliek** [comment]
@ghost, according to your screenshot you use port 4444 (10.76.159.209:4444)
selenium uses the same port (http://localhost:4444/wd/hub) 
and in .gemini.yml you can find the line:
`gridUrl` by default it is http://localhost:4444/wd/hub
