### ISSUE TITLE
mkdir error

### ISSUE THREAD

**Issue by pandoraizida** [gemini-testing/gemini#671]
Hi.

On ubuntu, with locators like '.header-menu.header-menu__left > ul > li:nth-child(1) > a' i has error, when gimin trying to create directory for screenshot
EPROTO: protocol error, mkdir '.header-menu.header-menu__left > ul > li:nth-child(1) > a'

Can you make names for directories with base64, or somethign similar?
Thank you.

**Comment by sipayRT** [comment]
so your suite has name `'.header-menu.header-menu__left > ul > li:nth-child(1) > a'`?

**Comment by DudaGod** [comment]
@pandoraizida to my mind it's strange desire.
Why you don't want use a more understandable name?

And I don't understand if suite name will be in base64 how you understand which a suite has failed?

**Comment by kkochetov** [comment]
@sipayRT @DudaGod 
it`s not a suite name. it`s locator.
As i understand, gemini make directory structure like this:
suite\locator\chrome.png

problem with locator directory.
base64 make LmhlYWRlci1tZW51LmhlYWRlci1tZW51X19sZWZ0ID4gdWwgPiBsaTpudGgtY2hpbGQoMSkgPiBh from '.header-menu.header-menu__left > ul > li:nth-child(1) > a'
this more correct for directory name than locator.
and we always can decode locator from base64.

**Comment by sipayRT** [comment]
@kkochetov no, you're wrong. structure will be `suite-name/state-name/browser.png`. It makes no sense to generate directories with base64 because all suites are unique.
