### ISSUE TITLE
Add hooks in configuration to run stuff before and after tests are running

### ISSUE THREAD

**Issue by GuyMograbi** [gemini-testing/gemini#693]
Similar to protractor's ` beforeLaunch?: () => void;` , ` onPrepare?: () => void;` , `onComplete?: () => void;` and such, 

This makes it much easier to setup your project. For example
beforeLaunch - run your server 
onComplete - kill your server. 

right now I need to write a bash script that will do everything

**Comment by sipayRT** [comment]
you need only write your own plugin for it - https://github.com/gemini-testing/gemini/blob/master/README.md#plugins
You can subscribe to events and start your server without any bash scripts

**Comment by GuyMograbi** [comment]
Awesome! thanks so much for the fast response. the project is awesome, keep up the good work!

**Comment by sipayRT** [comment]
tnx :)
