### ISSUE TITLE
Custom JS config file provided from CLI option does not resolve correctly

### ISSUE THREAD

**Issue by mad-gooze** [gemini-testing/gemini#704]
If you pass js file via `--config` option, it is resolved incorrectly [here](https://github.com/gemini-testing/gemini/blob/master/lib/config/config-reader.js#L31) as`require()` will search it against `__dirname`, which is `node_modules/gemini/lib/config`.

**Comment by tormozz48** [comment]
@mad-gooze Thank you for your issue.

It seems to be an error. Do you want to send a pull-request with fix of this issue?

**Comment by mad-gooze** [comment]
@tormozz48 pull-request is #705

**Comment by umbobabo** [comment]
I can confirm the same error.
