### ISSUE TITLE
Exclude certain test suites from a browser

### ISSUE THREAD

**Issue by bruk1977** [gemini-testing/gemini#713]
It would be nice, if there is a way to exclude certain test suites from a browser.

For example, I support feature-A only on modern browsers. Then I won't run that feature test suite on older browser like IE9, IE8... but everything else will run on those older browsers.

Right now, looks like all test suites will run on all browsers configured in gemini config file.

**Comment by sipayRT** [comment]
hi. You can use `suite.browsers()` method to run tests in specific browsers. See docs - https://github.com/gemini-testing/gemini/blob/master/doc/tests.md#suite-builder-methods
For example,

```
suite.browsers(['chrome', 'firefox']);
```
