### ISSUE TITLE
'Copy to clipboard' button for url in meta-info

### ISSUE THREAD

**Issue by mad-gooze** [gemini-testing/gemini#717]
Hi! 

I would like to suggest an enhancement for gemini html reports. It would be great to have a 'Copy to clipboard' button in html report near `meta-info`, which would copy the `url` field of the test to quickly open it in browser.

-------------------

Привет!

У меня есть предложение, как сделать html-репорты в gemini чуточку удобнее - было бы очень здорово сделать кнопку для копирования `url` теста из `meta-info`, чтобы можно было быстро открыть страницу в браузере.

**Comment by sipayRT** [comment]
привет. так ты можешь нажать на "глазик", чтобы открыть урл теста (а в инпуте ты можешь переопределить и домен для открытия урла)
![image](https://cloud.githubusercontent.com/assets/1658415/22111819/d0b42680-de71-11e6-8ae6-27f802c9f880.png)

**Comment by mad-gooze** [comment]
точно, не заметил, спасибо!
