### ISSUE TITLE
Font resolution differences

### ISSUE THREAD

**Issue by jadekler** [gemini-testing/gemini#732]
Hello! Thanks for gemini, we love it. We're running into a problem where images generated on Mac OSX seem to have a different DPI/resolution than images generated headless on Ubuntu with `xvfb-run` (X11 server):

![screen shot 2017-02-10 at 2 39 55 pm](https://cloud.githubusercontent.com/assets/3584893/22845255/f3e28a3c-ef9e-11e6-91c7-2061daeff1fe.png)

Anyone have an intuition or idea as to how we might fix this?

Thanks!

**Comment by puzankov** [comment]
We have same problems due to different OS of our devs (mac, ubuntu, windows). We solved this problem by using dockerised browser. We using now `selenium/standalone-chrome:3.0.1-germanium`

**Comment by bjornicus** [comment]
@puzankov thanks for the tip.  Do you happen to have a link to something you followed to set that up, or an open source example of a project that is set up that way? 

A bit of searching found this: https://hub.docker.com/r/roukmoute/testing-gemini/ which seems like a promising setup, but interested to know what easy to set up solutions worked for others (and how to replicate them).

**Comment by sipayRT** [comment]
also you can use some common grid to avoid such problems. For example, https://saucelabs.com

**Comment by renestalder** [comment]
That's not necessary Gemini related. I can tell you, that happens with every form of visual regression testing. I recommend that you create the reference screenshots on the same system that is making the actual tests. So when you're using a CI/CD system that tests your screenshot for differences, also use the CI/CD system to generate the reference screenshots.

In my case with GitLab, I define a job to create new screenshots and commit/push them with a bot and never create local screenshots.
