### ISSUE TITLE
selenium.NoSuchSessionException: no such session

### ISSUE THREAD

**Issue by limonte** [gemini-testing/gemini#741]
```
19:13:01.447 INFO - Executing: [get: about:blank])
19:13:01.536 WARN - Exception thrown
org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 49 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'testing-docker-21e9cd5b-8929-4cd2-87b0-bfbc85f3a8a4', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.12-040812-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64), platform=ANY}]
```

Output of `gemini --version`:

4.18.1

Contents of `.gemini.js` file:

```js
module.exports = {
  rootUrl: 'https://limonte.github.io/sweetalert2/',
  gridUrl: 'http://127.0.0.1:4444/wd/hub',
  screenshotsDir: './test/gemini/screens',

  browsers: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    }
  }
}
```

Test source code:

```js
gemini.suite('basic', (suite) => {
  suite.setUrl('/')
    .setCaptureElements('.swal2-modal')
    .capture('html-content', (actions, find) => {
      actions.click(find('.html button'))
      actions.wait(300)
    })
})
```

Command used to run the test:

```
selenium-standalone install
selenium-standalone start
gemini test test/gemini
```

You can see the result in Travis build: https://travis-ci.org/limonte/sweetalert2/builds/203557242

`.travis.yml` is here: https://github.com/limonte/sweetalert2/blob/visual-testing/gemini/.travis.yml

**Comment by rostik404** [comment]
Hello!
As I know, you can't launch browsers in travis, you should use [Sauce Labs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-Sauce-Labs)

**Comment by frbk** [comment]
Hey @limonte,

Try using xvfb. Here are the instruction on how to set it up with travis: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by limonte** [comment]
@rostik404 

> Hello!
As I know, you can't launch browsers in travis, you should use Sauce Labs

You can. Say hi to Selenium :)

@frbk 

> Try using xvfb.

I'm using it, please take a look on links from my question:  https://github.com/limonte/sweetalert2/blob/visual-testing/gemini/.travis.yml#L21
