### ISSUE TITLE
Unable to install gemini in Windows 10

### ISSUE THREAD

**Issue by gopalisoft** [gemini-testing/gemini#743]
Unable to install gemini in Windows 10. Following error is displaying
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exit
ed with code -1073741701. [C:\Users\test\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\third_part
y\libpng\libpng.vcxproj]

Tried to install gemini in administrator login also.
npm install -g gemini

However I am able to install selenium-standalone server

**Comment by sipayRT** [comment]
hi. check dependencies requirements - https://github.com/gemini-testing/gemini#dependencies. its looks like you do not have Compiler with support for C++11

**Comment by gopalisoft** [comment]
Thanks. Sorry I am new to Gemini and Windows 10. Do I need to download GCC from tdm-gcc.tdragon.net/download?  Can you recommend any site for this?

**Comment by gopalisoft** [comment]
I am able to install Gemini finally. I used tdm-gcc for compiler and restarted the system before installing gemini. Thanks for your support
