### ISSUE TITLE
Error "Path must be a string" with --html-reporter-path option

### ISSUE THREAD

**Issue by mubinov** [gemini-testing/gemini#759]
Hi,

It seems to me that option `--html-reporter-path` in cli is not working.

When I run code from [documentation](https://gemini-testing.github.io/doc/commands.html):
`gemini test --reporter html --html-reporter-path=tmp/gemini-reports`

I recieve this error: `TypeError: Path must be a string. Received [ 'tmp/gemini-reports' ]`.

I tried to write this option in any styles: absolute path, in double quotes, in single quotes, but in any case I receive that error.

**Comment by mubinov** [comment]
Fixing this issue is really easy, but this fix will have conflict with useful PR #751 . I will wait approving of this PR.

**Comment by eGavr** [comment]
html-reporter is now a separate [plugin](https://github.com/gemini-testing/html-reporter) and this feature works well in it :)
