### ISSUE TITLE
how do I clear a text input?

### ISSUE THREAD

**Issue by hyusetiawan** [gemini-testing/gemini#767]
looked around the docs and i could not find any hints, the only hint i got is the request to expose full selenium API  #654

**Comment by sipayRT** [comment]
hi.
there are no such API, but you can do it with `executeJS` method

**Comment by hyusetiawan** [comment]
Turns out I can easily monkey patch the actions, and create a proxy to the underlying selenium API. I really wish _pushAction and findElement are not private however, it would be more easier to extend its capabilities.
As a side note, I benchmarked my productivity, subjectively, by writing a selenium test and then write the same test in gemini. I am able to cover much more tests with MUCH less code with gemini, I am honestly surprised why this is tool is not more visible among developers. Is it still being actively used at yandex?

**Comment by eGavr** [comment]
> I am able to cover much more tests with MUCH less code with gemini

Glad to hear this

> I am honestly surprised why this is tool is not more visible among developers

Perhaps this is because we do not spend a lot of time on marketing

Is it still being actively used at yandex?

Yep, gemini is widely used at yandex
