### ISSUE TITLE
Incorrect parse of options with numbers

### ISSUE THREAD

**Issue by Yeti-or** [gemini-testing/gemini#769]
```
gemini --version
4.19.1
```
```
gemini --browsers-ie11-root-url desktop.react-tests
```
doesn't ovveride root-url
but
```
gemini --browsers-ie-eleven-root-url desktop.react-tests
```
Does

So I think we have problem with Numbers inside options `ie11` vc `ie-eleven`

**Comment by rostik404** [comment]
Hello!
It's seems like you passed incorrect option in the first case.
Try to use `--browsers-ie-11-root-url` option (dash between ie and 11).

**Comment by Yeti-or** [comment]
Thanx guys =)
