### ISSUE TITLE
How can I know what version of Selenium Remote Webdriver Gemini uses?

### ISSUE THREAD

**Issue by bruk1977** [gemini-testing/gemini#770]
Hi,

I setup a local grid and when I run my gemini test I'm getting the below error. 

```
[init({"browser":"Chrome","version":"57","os":"Windows","os_version":"10")] The environment you requested was unavailable..
Reason: HTTP ERROR: 500 Problem accessing /wd/hub/session. Reason: java.lang.NullPointerException Powered by Jetty:// 9.3.z-SNAPSHOT
```

For internal reason, the grid is only working with Selenium Webdriver 3.1. And looks like Gemini is using/expecting the latest Grid, which is 3.4.

Where is the selenium wedbdriver version configured in Gemini? I was expecting in WD dependency but don't see it there...

Please help me by pointing...

Thanks,
Bruk

**Comment by eGavr** [comment]
> And looks like Gemini is using/expecting the latest Grid

In a good questions there is an answer :)

> Where is the selenium wedbdriver version configured in Gemini?

There is no such place in gemini. gemini uses a module [wd](https://github.com/admc/wd) which (as in its description goes) is a node.js client for **webdriver/selenium 2**.
