### ISSUE TITLE
Will you support Chrome headless ?

### ISSUE THREAD

**Issue by davenlin19** [gemini-testing/gemini#775]
Chrome headless will coming with the version 59 and it seems PhantomJS'll be abandonned. Do you plan to support Chrome headless ?

**Comment by sipayRT** [comment]
maybe, but not in the nearest future

**Comment by tk8817** [comment]
I am a bit confused, doesn't gemini intrinsically support it as a result of supporting Selenium/Chromedriver? 

All you need to do as a user is pass the `--headless` flag as a startup switch.

**Comment by sipayRT** [comment]
> I am a bit confused, doesn't gemini intrinsically support it as a result of supporting Selenium/Chromedriver?

gemini support only communication with browser, but not browser configuration on such level

**Comment by eGavr** [comment]
@tk8817 @davenlin19 

> I am a bit confused, doesn't gemini intrinsically support it as a result of supporting Selenium/Chromedriver?

I think that you are right :)

I've surfed the web and it seems that this feature can be configured via `desiredCapabilities` in gemini config:

```js
module.exports = {
    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
                version: '59.0',
                chromeOptions: {
                    args: ['--headless']
                }
            }
        }
    }
};
```

**Comment by tk8817** [comment]
@eGavr - exactly! I am not a Gemini user, but it would be very strange if such a config was not possible. A lot of people will be very excited by your find.

**Comment by eGavr** [comment]
@davenlin19 

Have you solved your problem by passing `chromeOptions: { args: ['--headless']}` in desiredCapabilities ?

**Comment by eGavr** [comment]
@davenlin19 @tk8817 

With the help of our selenium team I've run tests in chrome@59 headless. You need a virtual linux machine, on this machine do the following:

1. Download a binary of chromedriver
2. Download a binary of chrome@59
3. Run chromedriver: `./chromedriver --port=4444 --whitelisted-ips='' --verbose`
4. `gridUrl` will be `http://<name-of-your-machine>:4444`

on your local machine configure a simple project with `gemini@5.0.0-alpha.4`:

package.json:

```json
{
  "name": "gemini_test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gemini": "^5.0.0-alpha.4",
    "html-reporter": "^0.2.0"
  }
}
```

.gemini.js:

```js
module.exports = {
    rootUrl: 'https://lodash.com',
    gridUrl: 'http://<name-of-your-machine>:4444', // without '/wd/hub'

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                version: '59.0',
                chromeOptions: {
                    args: ['headless']
                }
            }
        }
    },

    system: {
        plugins: {
            'html-reporter': {
                enabled: true,
                path: 'gemini-report'
            }
        }
    }
};
```

gemini/index.gemini.js:

```js
gemini.suite('lodash-docs', (suite) => {
    suite.setUrl('/docs')
        .setCaptureElements('body')
        .capture('plain');
});
```

Run:

```js
./node_modules/.bin/gemini update && ./node_modules/.bin/gemini test
```

See gemini html report in `gemini-report/index.html`.
