### ISSUE TITLE
On click of button with transition

### ISSUE THREAD

**Issue by ballwood** [gemini-testing/gemini#790]
Hi,

We're using Gemini to run some visual regression checks on our app and it's been working great so far. 

We've got a problem however with a button that has CSS on it that performs a transition between colors on click. What seems to be happening is Gemini doesn't take the screenshot at the same consistent time each run so when comparing to the original it fails as the color is not correct as it hasn't fully transitioned. 

Is there any sort of workaround we can use so we can fix this?

Cheers

**Comment by eGavr** [comment]
@ballwood Can you provide a minimally reproducible case, please? This will help to solve your problem faster.

**Comment by ballwood** [comment]
Yeah no problem I'll try and put something together tomorrow

**Comment by ballwood** [comment]
Hi seems it was an issue our end. Apologies!
