### ISSUE TITLE
Capture multiple elements on page

### ISSUE THREAD

**Issue by artemyarulin** [gemini-testing/gemini#798]
Hi, is there any way to capture multiple elements using one selector? 

I have a page with all components available in our project and was thinking to cover those with gemini, but following code:

```
gemini.suite('components', suite => {
  suite
    .setUrl('/components')
    .setCaptureElements('.component') // page has many blocks with .component class which I would like to capture
    .capture('normal')
})
```
Does capture only first component, while I was expecting having an array of screenshots as the result. There are two workaround that I found:
1) setCaptureElements to full page, but then screenshot would be really big (we have hundred of components)
2) Write test manually for each component - would take too much time.

Is there any better way for that?

**Comment by artemyarulin** [comment]
Found a good enough solution:
``` js
const componentCount = 2

new Array(componentCount).fill(0).map((_,idx) => {
  gemini.suite('component_' + idx, suite => {
    suite
      .setUrl('/components')
      .setCaptureElements(`.component:nth-child(${idx+1})`)
      .capture('normal')
  })
})
```

Thank you for your awesome project!

**Comment by cameron-martin** [comment]
I'm afraid this isn't a good enough solution for me because the elements that I want to take a screenshot of don't have the same parent. My use case is automatically taking screenshots of all examples in a react-styleguidist project.

The best solution that I've come to so far is wrapping each example in a div with a `data-example-id` attribute, which is an incrementing id. I then specify the example count in the gemini tests and then create examples in a loop. However, this means you need to update the example count manually each time you add an example which is far from ideal.

Can this issue be re-opened?

**Comment by artemyarulin** [comment]
Yeah, we eventually gave up on updating counter manually. Solved via helper script which we run before gemini tests, looks like that:
```js
import React from 'react'
import {shallow} from 'enzyme'
import DevCards from '../DevCards'
import {writeFileSync} from 'fs'
import * as path from 'path'

test('Uitest generator', () => {
  const comp = shallow(<DevCards />)
  const cards = comp
    .children()
    .children()
    .children()
  const titles = cards.map(c => c.shallow().nodes[0].props.name) // some magic to get names for UI test screenshots
  writeFileSync(path.join(__dirname, 'devcards.json'), JSON.stringify(titles))
})
```

Then we use generated data in Gemini test:
```js
const readFileSync = require('fs').readFileSync
const path = require('path')
const devCardTitles = JSON.parse(readFileSync(path.join(__dirname, 'devcards.json')))

devCardTitles.map(title => title.replace(/[^a-zA-Z0-9]/g, '_')).map((title, idx) => {
  gemini.suite('Fuels_' + title, suite => {
    const selector = `.vapo-card:nth-child(${idx + 1}) *:nth-child(2)`
    suite
      .setUrl('/devcards')
      .setCaptureElements(selector)
      .capture('normal', (actions, find) =>
        actions
          .wait(2000)
          .mouseMove(selector)
          .wait(200)
          .logs(errMessages => {
            if (errMessages.length)
              throw new Error(
                'Unexpected console.error or console.warnings\n ' +
                  errMessages.map(l => l.message).join('\n')
              )
          })
      )
  })
})
```

Something like that
