### ISSUE TITLE
Unable to install Gemini in my windows system

### ISSUE THREAD

**Issue by kittyPillai** [gemini-testing/gemini#803]
Hello,

I am new to Gemini and wanted to give it a try, having read a lot about it.
However, I am facing issues when installing it. I am trying to install gemini on my windows 7 machine using the command "npm install -g gemini". The installation seems to halt when trying to install png-img and I have tried installing visual studio 2017 version to resolve the issue. However, I read somewhere that png-img is not windows compatible. Could you please let me know what I am doing wrong in the installation.

Please find the output below

C:\Users\kirti.vm\AppData\Roaming\npm\gemini -> C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\bin\gemini

> png-img@2.1.1 install C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img
> node-gyp rebuild

C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C4430: missing type specifier - int assumed. Note: C++ does not suppor
t default-int [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2440: 'initializing' : cannot convert from 'PfnDliHook' to 'int' [C:\
Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2146: syntax error : missing ';' before identifier '__pfnDliNotifyHoo
k2' [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C4430: missing type specifier - int assumed. Note: C++ does not suppor
t default-int [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2373: '__pfnDliNotifyHook2' : redefinition; different type modifiers
[C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2440: 'initializing' : cannot convert from 'FARPROC (__cdecl *)(unsig
ned int,DelayLoadInfo *)' to 'int' [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C4430: missing type specifier - int assumed. Note: C++ does not suppor
t default-int [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2440: 'initializing' : cannot convert from 'PfnDliHook' to 'int' [C:\
Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2146: syntax error : missing ';' before identifier '__pfnDliNotifyHoo
k2' [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C4430: missing type specifier - int assumed. Note: C++ does not suppor
t default-int [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2373: '__pfnDliNotifyHook2' : redefinition; different type modifiers
[C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
..\..\..\..\..\..\..\..\..\..\..\..\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(34): error C2440: 'initializing' : cannot convert from 'FARPROC (__cdecl *)(unsig
ned int,DelayLoadInfo *)' to 'int' [C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kirti.vm\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\kirti.vm\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gemini"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! png-img@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@2.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the png-img package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

==============================

**Comment by sipayRT** [comment]
hi

it's probably because of node-gyp. maybe [this link](https://github.com/nodejs/node-gyp#on-windows) can help you

**Comment by kittyPillai** [comment]
Hi,

Thank you, your solution has worked. I have successfully installed Gemini.
