### ISSUE TITLE
Expose console messages

### ISSUE THREAD

**Issue by artemyarulin** [gemini-testing/gemini#816]
We are working with React components and now and then developers tend to forget updating propTypes. React then in runtime would `console.error` about that, but with Gemini there is no access to read console messages back to the tests. There are many other cases when browsers emit warnings and I think it's in scope of Gemini to provide API for reading that. Is there any workaround for that?

Just for reference here for example how it could be done with direct access to webdriver for Chrome:
``` js
const webdriver = require('selenium-webdriver'),
      logging = require('selenium-webdriver/lib/logging'),
      chrome = require('selenium-webdriver/chrome')

const opts = new chrome.Options()
opts.addArguments('no-sandbox')
const prefs = new logging.Preferences()
prefs.setLevel(logging.Type.BROWSER, logging.Level.ERROR)
const caps = webdriver.Capabilities.chrome()
caps.setLoggingPrefs(prefs)
const webdriver = new webdriver
     .Builder()
     .forBrowser('chrome')
     .setChromeOptions(opts)
     .withCapabilities(caps)
     .build()

webdriver
  .then(browser => browser.get('http://localhost:8080'))
  .then(() => driver.manage().logs().get(logging.Type.BROWSER))
  .then(logs => {
    if (logs.length)
      throw new Error('console.error messages found')
  })

**Comment by artemyarulin** [comment]
Do you guys agree to accept PR for that? I've implemented it already in my fork, essentially it's this commit https://github.com/gemini-testing/gemini/commit/a4a9618af18b6f5d78f32eb04ae403bc6e5c8bff

**Comment by sipayRT** [comment]
Hi.
Sorry for delay.
Yes, you can send us your PR - we'll merge it

**Comment by artemyarulin** [comment]
Cool, thanks! I'll do it in a proper way and update docs as well some time later 👍

**Comment by vinayakpatil** [comment]
@artemyarulin Does it work with you changes shared in https://github.com/gemini-testing/gemini/commit/a4a9618af18b6f5d78f32eb04ae403bc6e5c8bff?

**Comment by artemyarulin** [comment]
Hi, haven't used this project for a while, don't even remember, but most probably yeah, closing :)

**Comment by vinayakpatil** [comment]
We are looking into a way to capture browser logs for accessibility testing through `axe-core`, I am unable to figure out a way to do so.

**Comment by vinayakpatil** [comment]
Following snippet seems to work

```
.capture('default', (actions) => {
          actions.executeJS(function(window) {
            window.axe.run(function(error, results) {
              console.error('A11Y:' + JSON.stringify(results.violations));
            });
          }).wait(3000).logs(function(logs) {
            console.error(logs.filter((log) => log.level === 'SEVERE' && log.message.indexOf('A11Y:') > -1)[0]);
          });
        })
```
