### ISSUE TITLE
Is it possible to set viewport instead of windowSize?

### ISSUE THREAD

**Issue by ganlanyuan** [gemini-testing/gemini#823]
View port is much meaningful than window size. 
When I set `windowSize` to 1024x768, I actually get the view port at size 991x768 which is not what I expected. If I can set the view port directly, it will be very helpful.
Thanks

**Comment by sipayRT** [comment]
no, there are no such ability because you need to do one more request to browser to calculate sizes for viewport. It's redundantly.
You can do it yourself in test by getting current viewport size and change window size you need

**Comment by ganlanyuan** [comment]
I see, thank you

-------- Original Message --------
