### ISSUE TITLE
Root url paramter in the config not working properly.

### ISSUE THREAD

**Issue by badaldesai** [gemini-testing/gemini#827]
Output of `gemini --version`:

5.0.0-alpha.8

Contents of `.gemini.yml` file:

```{
    "rootUrl": "http://localhost:3000/src/index.html?configFile=../test/config/",
    "gridUrl": "http://127.0.0.1:4444/wd/hub",
    "windowSize": "1600x1080",
    "compositeImage": true,
    "browsers": {
      "chrome": {
        "desiredCapabilities": {
          "browserName": "chrome",
          "chromeOptions": {
            "args": [ "--headless" ]
          }
        }
      }
    },
    "system": {
      "projectRoot": "./test",
      "plugins": {
        "html-reporter": {
          "path": "test/gemini-report"
        }
      }
    }
  }

```

Test source code:

```gemini.suite('test.json', (suite) => {
        suite.setUrl(key)
            .setCaptureElements('body')
            .capture('desktop', actions => {
                // Added wait as some of the webpage takes some time to load properly.
                actions.wait(500);
            })
            .capture('mobile', (actions) => {
                actions.setWindowSize(350, 600);
            })
            .capture('tablet', (actions) => {
                actions.setWindowSize(768, 1024);
            });
    });

```

Command used to run the test:

```
gemini.test(`${__dirname}/gemini_suites.js`, {
        reporters: ['flat'],
    });
```

Result:

After the update, browser opens a webpage with url: http://localhost:3000/src/test.json

Expected behaviour:

It should open browser with url: http://localhost:3000/src/index.html?configFile=../test/config/test.json
This behaviour used to work properly with gemini version 4.9.2. After i updated to 5.0.0-alpha.8, i started getting this issue.

**Comment by sipayRT** [comment]
hi

but you trying to add `test.json` part to your query, not to url. gemini works with url not as a simple string. So your `test.json` part will not be concatted to the rootUrl. you can write some helper for url generation

**Comment by badaldesai** [comment]
I already wrote helper function to generate url to test, but it generates screenshot with whole directory tree and whole name of the file such `index.html?configFile=..` -> `test` -> `config` -> `test.json`. So is there way to define the name of the screenshot just not create directory tree?
