### ISSUE TITLE
Рандомное не соответствие между эталонными и тестовыми скриншотами

### ISSUE THREAD

**Issue by StasGrishaev** [gemini-testing/gemini#857]
Добрый день. никак не получается избавиться от _рандомного_ расхождения между эталонными скриншотами и тестовыми - периодически возникает в любом из трёх используемых браузерах, в разных элементах ( замечено что в основном в шрифтах ). пробовал менять `tollerance` - не помогло, пробовал включать-отключать `callibrate` - тоже не дало эффекта. Что можете ещё посоветовать ? Прикладываю скриншоты для элементов с которыми возникают проблемы.

![2017-12-20_1406_001](https://user-images.githubusercontent.com/19959547/34204257-08644d10-e58f-11e7-9299-f82d1c2c30f3.png)
![2017-12-20_1406](https://user-images.githubusercontent.com/19959547/34204258-087cda38-e58f-11e7-8bc8-e7e2d91b734a.png)

Output of `gemini --version`:

5.0.0-alpha.10

Contents of `.gemini.js` file:

```js
module.exports = {
    rootUrl: 'http://localhost:9000',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',
    sessionsPerBrowser: 1,

    browsers: {
        chrome: {
            screenshotsDir: './gemini/chrome-screens',
            windowSize: '1920x1080',
            compositeImage: true,
            // calibrate: false,
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        firefox:{
            windowSize: '1920x1080',
            screenshotsDir: './gemini/ff-screens',
            // calibrate: true,
            desiredCapabilities:{
                browserName: 'firefox',
                marionette: false
            }
        },
        // ie:{
        //     windowSize: '1920x1080',
        //     screenshotsDir: './gemini/ie-screens',
        //     calibrate: true,
        //     desiredCapabilities:{
        //         browserName: 'internet explorer',
        //     }
        // },
        edge:{
        	windowSize: '1920x1080',
            screenshotsDir: './gemini/edge-screens',
            compositeImage: true,
            calibrate: false,
            desiredCapabilities:{
                browserName: 'MicrosoftEdge'
            }
        }
    },

    sets:{
    	chrome:{
    		files:"C:/Users/User/Documents/project/__test__/css_regression"
    	},
    	// firefox:{
    	// 	files:"C:/Users/User/Documents/project/__test__/css_regression"
    	// },
    }
};
```

Test source code:

```js
gemini.suite( "registry", function( suite ) {

	/**
	 *  Suite: Check of Login page
	 */
	suite.setUrl( "/#/members" )
	     .before( function( actions ) {
		     actions.waitForElementToShow( ".results-count.ng-binding", 35000 );
		     actions.wait(5000);
	     } )
	     .setCaptureElements( [
		     ".content.page-content"
	     ] )
	     .capture("plain");
} );
```

Command used to run the test:

```
gemini-gui
```

**Comment by j0tunn** [comment]
@StasGrishaev привет. Можешь кинуть пары reference-actual для этих диффов? Похоже, что там реально смещение присутствует

**Comment by StasGrishaev** [comment]
@j0tunn сойдёт если не все скриншоты целиком ? не могу светить проект в открытом доступе. 
так же если необходимо ( если чем то поможет ) могу все CSS атрибуты для этих элементов прислать или скрин DOM дерева.

**Comment by DudaGod** [comment]
Пойдут такие же самые скриншоты, но только где можно увидеть reference - actual - diff.

**Comment by StasGrishaev** [comment]
@DudaGod принято, ловите : 

**reference** - ![image](https://user-images.githubusercontent.com/19959547/34208293-fbd68a1c-e59e-11e7-8329-47f03737f548.png)
**current** - ![image](https://user-images.githubusercontent.com/19959547/34208307-0dfbb910-e59f-11e7-97c0-a380d4fea7b0.png)
**diff** - ![image](https://user-images.githubusercontent.com/19959547/34208326-1d5502b8-e59f-11e7-8562-635cd4bcd3f9.png)

**reference** - ![image](https://user-images.githubusercontent.com/19959547/34208359-3cd86094-e59f-11e7-8572-d7e3b387afd4.png)
**current** - ![image](https://user-images.githubusercontent.com/19959547/34208401-4d4da2ae-e59f-11e7-8ecb-d9d576ab5f26.png)
**diff** - ![image](https://user-images.githubusercontent.com/19959547/34208421-575cb000-e59f-11e7-9f90-e57eb17a9e8c.png)

**Comment by DudaGod** [comment]
@StasGrishaev нужно чтобы они одинакового размера были. А ты их повырезал разного размера и не увидишь сходу дифф.

**Comment by DudaGod** [comment]
через фотошоп наложили друг на другу получили следующее: https://2.downloader.disk.yandex.ru/disk/2aab352076956a968daaae942950b11824751c4c86ca88b0c095384c0ace558d/5a3aa15f/sT1QdcSRiNahJYUfrxwvj5-bT6lGFZTHlqIIFtwOSmM2-KYC5Ywwn8DD8TerEe46cOyJZX5vpuk3Ontmqbd-LQ%3D%3D?uid=0&filename=Animation.gif&disposition=inline&hash=&limit=0&content_type=image%2Fgif&fsize=8620&hid=8540c64471f53c864bac72893c0916f8&media_type=image&tknv=v2&etag=7ba9f11b01abbdf61ca90132898c132f

Видно как элемент двигается, проблема в твоем коде.

**Comment by StasGrishaev** [comment]
@DudaGod как раз занимался тем чтобы вырезать одинаковые по размеру куски и заметил эти движение. с этим случае согласен, но очевидно что это не критичное отклонение и можно ли заставить скрипт не падать при таком небольшом отклонении ? 
а что вы скажете по поводу падения на цифре 1 ( второй пример ) ?

**Comment by j0tunn** [comment]
@StasGrishaev В общем случае в таких кейсах мы делаем из двух изображений гифку, и смотрим что там меняется. Если изменение заметно глазу - значит это нормально, что тест падает, значит есть баг

**Comment by j0tunn** [comment]
gemini не умеет игнорировать смещение. Оснвная цель - это как раз находить подобные смещения

**Comment by StasGrishaev** [comment]
@j0tunn обидно. тут на лицо то ли какая то хитрость рендеринга, то ли... не знаю, может построения DOM дерева. 
я так и не понял в чём разница во втором моём примере, с единицей в круге.

**Comment by j0tunn** [comment]
> посмотрел ещё раз очень внимательно - есть микроскопическое отличие по положению элемента.

такое часто бывает, если:
- размер окна браузера изменился (лечится просто переснятием эталона)
- положение всего блока на странице изменилось (лечится переснятием эталона)
- в коде, определяющем положение элемента на странице есть манипуляции с дробными числами и округление (срабатывание в таком случае показыват, что в коде есть баг)

> крайне неудобно что из за такой мелочится фейлится проверка. нельзя ли вынести отдельный параметр в конфиг для увеличения "толлерантности" таких случае, но именно в плане сдвигов элементов, а не цветов ?

- такая мелочь показывает, что на странице случился сдвиг, т.е. в принципе что-то изменилось
- tolerance на сдвиг не влияет вообще никак. Он влияет на сравнение пикселей, находящихся В ОДНОМ месте. Можно, конечно, выставить tolerance в 100, но тогда gemini просто не будет вообще ничего проверять
- возможность задавать в конфиге допустимый сдвиг - отдельная очень нетривиальная задача с кучей вопросов (например допустимо ли, если все элементы на странице сдвинулись на пиксель в сторону)

**Comment by StasGrishaev** [comment]
@j0tunn принято, спасибо !

**Comment by j0tunn** [comment]
@StasGrishaev если не сложно, как разберешься - отпишись. Думаю эта информация будет полезной как нам, так и тем, кто сюда заглянет после

**Comment by StasGrishaev** [comment]
@j0tunn пока что решил просто заигнорить эти проблемные элементы через `ignoreElements` - другого выхода пока не нашёл.
