### ISSUE TITLE
Pass more build info to SauceLabs

### ISSUE THREAD

**Issue by arikon** [gemini-testing/gemini#9]
We could detect we are using SauceLabs for test running and automatically set-up `tunnel-identifier` (using `TRAVIS_JOB_NUMBER`) and `build` (using `TRAVIS_BUILD_NUMBER`) capabilities.

**Comment by j0tunn** [comment]
Resolved via [gemini-saucelabs-info](https://github.com/gemini-testing/gemini-saucelabs-info) plugin
