### ISSUE TITLE
Установка на Windows 10 / Installing on Windows 10

### ISSUE THREAD

**Issue by wayheming** [gemini-testing/gemini#909]
Здравствуйте комюнити прошу вашей любой помощи в установке Gemini на Windows 10. Сейчас столкнулся с такой проблемой и не знаю что делать дальше гугл не помогает. Подскажите что я делаю не так?

Hello comity, I ask your any help in installing Gemini on Windows 10. Now I encounter such a problem and I do not know what to do next Google does not help. Tell me what I'm doing wrong?

https://prnt.sc/j85x9n
https://prnt.sc/j85xc4

**Comment by generalov** [comment]
Я устанавливал Node.JS 8.9.4 через https://github.com/coreybutler/nvm-windows. 
Чтобы завелся node-gyp https://github.com/felixrieseberg/windows-build-tools . 

Так же попробуй переименовать рабочую директорию, чтобы она не совпадала с названием пакета: `d:\work\gemini` -> `d:\work\my-gemini`. После чего создать в рабочей директории package.json: `npm init -y`.

Еще обрати внимание на https://github.com/gemini-testing/gemini/pull/906 .
