### ISSUE TITLE
Ошибка при выполнении команды gemini update

### ISSUE THREAD

**Issue by WalentinPawlow** [gemini-testing/gemini#910]
Здравствуйте!
Установил gemini на виртуальную машину с Ubuntu.
Далее действовал по инструкции Quick start из документации.
При попытке выполнить команду
gemini update
вываливается ошибка http://prntscr.com/ja5y51
Помогите разобраться с проблемой

**Comment by DudaGod** [comment]
Привет.
А какая у тебя версия ноды? Судя по ошибке тебе нужно обновить ее до 6ой.

**Comment by WalentinPawlow** [comment]
Да, помогло. Стояла версия 4.6. Поставил 6.14.1 и ошибка пропала
