### ISSUE TITLE
Get UnknownKeysError: Unknown options: root.firefox on launching test

### ISSUE THREAD

**Issue by ezik** [gemini-testing/gemini#925]
Hello, I just started using Gemini. And really cannot understand what is wrong, trying to solve problem the 3rd day without luck.
On "gemini update" or "gemini test" commands I got following error:
Get UnknownKeysError: Unknown options: root.firefox

I use Mac book with MacOs High Sierra
Gemini is installed under my user profile to npm-global directory
Geckodriver is located in usr/local/bin

Output of `gemini --version`:
5.7.2
Npm version:
6.1.0
Selenium-standalone version:
Selenium build info: version: '3.12.0'
Geckodriver version:
0.21.0

**Directory hierarchy:**
.gemini.yml
gemini/test.js
screens
temp-images

**Contents of `.gemini.yml` file:**
rootUrl: http://yandex.ru
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./screens
firefox:
    desiredCapabilities:
      browserName: firefox
      version: "61.0"

**Test source code:**
var gemini =require('gemini');

gemini.suite('yandex-search', (suite) => {
    suite.setUrl('/')
        .setCaptureElements('.home-logo')
        .capture('plain');
});

Command used to run the test:
1) Launch selenium-standalone
selenium-standalone start
2) Then
gemini test
OR
gemini update

Expected behaviour:
Launch test succesfully

**Comment by sipayRT** [comment]
Hi
See https://github.com/gemini-testing/gemini/blob/master/doc/config.md#gemini-configuration docs. You should move browser configuration to `browsers` section
