### ISSUE TITLE
[Question] Is it possible to set rootUrl in runtime?

### ISSUE THREAD

**Issue by alexeyoganezov** [gemini-testing/gemini#964]
Gemini is a great help for our project so far, but one thing makes its usage a little bit inconvenient: I'm speaking about setting `rootUrl` before test runs.

We have remote Selenoid server and we want to be able to start tests not only from CI-agents, but also from local developer environment that sometimes is placed in various networks. To solve an access problem (NAT/firewalls) we've developed [a plugin](https://github.com/alexeyoganezov/gemini-localtunnel) that creates a public tunnel from URL like [https://alexey.localtunnel.me](https://alexey.localtunnel.me) to local web-server and it works perfectly, but since we aren't able to change `rootUrl` in the plugin we have to do something like this:

__package.json__
```
"scripts": {
    "gemini": "gemini_root_url=\"http://$(hostname -s).localtunnel.me\" gemini test",
  },
```

This step would be completly unnecessary if we could do something like:

```
gemini.on(gemini.events.START_RUNNER, () => {
   const URL = getTunnel();
   gemini.config.rootUrl = URL;
});
```

But it doesn't work and I'd like to know if there is a way to set `rootUrl` somehow from plugin API. And if there isn't would you accept a pull request than enables this functionality?

**Comment by j0tunn** [comment]
Hi you should change `rootUrl` for each browser:
```js
gemini.on(events.START_RUNNER, async () => {
    const URL = getTunnel();

    gemini.config.getBrowserIds().forEach((id) => {
        const rootUrl = url.parse(gemini.config.forBrowser(id).rootUrl);

        gemini.config.forBrowser(id).rootUrl = url.format({
            host: URL,
            pathname: rootUrl && rootUrl.path || ''
        });
    });
});
```

All data in `gemini.config` - are just the default value for each browser config.

**Comment by j0tunn** [comment]
@alexeyoganezov and I'd suggest you to migrate to [hermione](https://github.com/gemini-testing/hermione). gemini will be deprecated soon

**Comment by alexeyoganezov** [comment]
Alright, we'll try it. Thank you for the fast response.
