### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Djo-djo** [gemini-testing/gemini#982]
Can't install on Windows 10.

![image](https://user-images.githubusercontent.com/27286407/83118405-fc073e00-a0d6-11ea-9aa8-7d80a86e9a29.png)

 I have python env variable and try [node-gyp](https://github.com/nodejs/node-gyp#on-windows)
![image](https://user-images.githubusercontent.com/27286407/83118534-2bb64600-a0d7-11ea-9c50-58de64fb7420.png)

**Comment by j0tunn** [comment]
Looks like node-gyp issue: https://github.com/nodejs/node-gyp/issues/2048

**Comment by Djo-djo** [comment]
Thanks
