### ISSUE TITLE
Can't use gemini command after install

### ISSUE THREAD

**Issue by Djo-djo** [gemini-testing/gemini#983]
I've installed gemini but can't use this command

![image](https://user-images.githubusercontent.com/27286407/83125343-1396f480-a0e0-11ea-9dd6-93475d22f280.png)

**Comment by j0tunn** [comment]
Its not about gemini but about npm itself. Search around the internet about "npm global modules path".
And you should not use gemini at all. It is deprecated. Take a look at notification in repository title: https://github.com/gemini-testing/gemini
